### ISSUE TITLE
pos_disable payment and multisession causes pos_pricelsit to crash

### ISSUE THREAD

**Issue by flotho** [itpp-labs/pos-addons#101]
Hi,

Don't really know if it's the correct place to report :
- https://github.com/OCA/pos/pull/83#issuecomment-202573012
- https://github.com/OCA/pos/pull/83#issuecomment-202580863

regards

**Comment by flotho** [comment]
Hi @yelizariev ,

I wouldn't spam the OCA repo so I post the issue here.
What is your point of view regarding the dependency conflict on this?

regards

**Comment by yelizariev** [comment]
@flotho I don't have a quick answer here. I need to reproduce the issue and make analysis.

**Comment by flotho** [comment]
Hi @yelizariev, any delay for this ? Need some financial help?

**Comment by yelizariev** [comment]
@flotho yes, we need a sponsorship to analyse the issue and make solution

**Comment by flotho** [comment]
what could be the cost?
I'm trying to setup a project on upwork

**Comment by flotho** [comment]
Did you reproduce?
Regards

**Comment by yelizariev** [comment]
I cannot reproduce it.
I install pos_disabple_payment, pos_multi_sesssion, pos_cache and POS loads without errors

**Comment by flotho** [comment]
I retried an have no more issues. My conf was probably bad. So this one could be closed
