### ISSUE TITLE
Printer Network POSBox

### ISSUE THREAD

**Issue by sm2x** [itpp-labs/pos-addons#1026]
Is POSBox a must or required to use **pos_network_printer**  ?
Also, is it compatible with iotbox?

**Comment by ilmir-k** [comment]
> Is POSBox a must or required to use pos_network_printer ?

No, you can configure another odoo instance instead. See the official manual (``POSBoxless Guide (advanced)`` section)
https://www.odoo.com/documentation/user/11.0/point_of_sale/overview/setup.html

> Also, is it compatible with iotbox?

Yes

**Comment by sm2x** [comment]
how about if your server is on the cloud, you have POS on the store using just Tablet and a network printer?

**Comment by woepwoep** [comment]
Network printer on the same local network as the Tablet.
IP of the network printer in the POS configuration of the Odoo instance in the cloud.
