### ISSUE TITLE
Tables deleted after resume session

### ISSUE THREAD

**Issue by dhecar** [itpp-labs/pos-addons#1081]
Hi, I have a problem with syncronization in multisession.

I have 4 phones + 3 tablets + central PC where i have the DB. All connected throuth the same router (pc with ethernet, phones with Wifi). Sometimes, one of the phones go to sleep mode or power save mode, when i restart this phone the tables of the main PC where deleted. 

The version of the odoo is the 10.  I have the latest code.

**Comment by Ramil-Mukhametzyanov** [comment]
@dhecar Thank you for your report. 
At the first test, we did not reproduce the problem.
We will continue testing. There may be a reason due to the behavior of the longpolling module.
