### ISSUE TITLE
[Odoo 12.0-20190727]  Module POS 

### ISSUE THREAD

**Issue by gochsman** [itpp-labs/pos-addons#1093]
I my odoo server version  12.0-20190727 a found a issue when a try edit the name of the POS or any feature about it  and the odoo never back to the menu main. 

The errors  is following:

web.assets_common.js:3456 error: Some modules could not be started
log @ web.assets_common.js:3456
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
add @ web.assets_common.js:797
(anonymous) @ web.assets_common.js:802
each @ web.assets_common.js:625
(anonymous) @ web.assets_common.js:802
Deferred @ web.assets_common.js:803
then @ web.assets_common.js:802
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:44
setTimeout (async)
_.delay @ web.assets_common.js:44
log_when_loaded @ web.assets_common.js:3469
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
ready @ web.assets_common.js:809
completed @ web.assets_common.js:810

web.assets_common.js:3456 Missing dependencies:     ["root.widget"]0: "root.widget"length: 1__proto__: Array(0)
log @ web.assets_common.js:3456
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
add @ web.assets_common.js:797
(anonymous) @ web.assets_common.js:802
each @ web.assets_common.js:625
(anonymous) @ web.assets_common.js:802
Deferred @ web.assets_common.js:803
then @ web.assets_common.js:802
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:44
setTimeout (async)
_.delay @ web.assets_common.js:44
log_when_loaded @ web.assets_common.js:3469
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
ready @ web.assets_common.js:809
completed @ web.assets_common.js:810

web.assets_common.js:3457 Failed modules:           ["web_editor.IframeRoot.instance"]0: "web_editor.IframeRoot.instance"length: 1__proto__: Array(0)
log @ web.assets_common.js:3457
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
add @ web.assets_common.js:797
(anonymous) @ web.assets_common.js:802
each @ web.assets_common.js:625
(anonymous) @ web.assets_common.js:802
Deferred @ web.assets_common.js:803
then @ web.assets_common.js:802
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:44
setTimeout (async)
_.delay @ web.assets_common.js:44
log_when_loaded @ web.assets_common.js:3469
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
ready @ web.assets_common.js:809
completed @ web.assets_common.js:810

web.assets_common.js:3460 Non loaded modules:       (2) ["web_tour.tour", "web_editor.tour"]0: "web_tour.tour"1: "web_editor.tour"length: 2__proto__: Array(0)
log @ web.assets_common.js:3460
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
add @ web.assets_common.js:797
(anonymous) @ web.assets_common.js:802
each @ web.assets_common.js:625
(anonymous) @ web.assets_common.js:802
Deferred @ web.assets_common.js:803
then @ web.assets_common.js:802
(anonymous) @ web.assets_common.js:3469
(anonymous) @ web.assets_common.js:44
setTimeout (async)
_.delay @ web.assets_common.js:44
log_when_loaded @ web.assets_common.js:3469
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
ready @ web.assets_common.js:809
completed @ web.assets_common.js:810

Thanks.

**Comment by trojikman** [comment]
It is not clear which module you are talking about. Feel free to reopen with additional information
