### ISSUE TITLE
[11.0] pos_orders_history_reprint There is no Ticket for the order.

### ISSUE THREAD

**Issue by ImplantiSolucoes** [itpp-labs/pos-addons#1122]
I'm getting the error "There is no Ticket for the order", analyzing the code I realized that is because the order is as "invoiced" and to reprint it must be "done", it would be interesting that if you put an OR

**Comment by Ramil-Mukhametzyanov** [comment]
@ImplantiSolucoes 
Hello, thank you for the report.

**Comment by Ramil-Mukhametzyanov** [comment]
Solved https://github.com/it-projects-llc/pos-addons/pull/1158
