### ISSUE TITLE
Multi_session error

### ISSUE THREAD

**Issue by jwcaceres** [itpp-labs/pos-addons#1146]
This is the error in multi_session module: 

Error: QWeb2 - template['PosTicket']: Runtime Error: TypeError: dict.order.changed.client is undefined
http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3374
Rastreo de error:
exception@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3374:7
anonymous@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js line 3416 > Function:156:29
_render@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3415:296
render@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3415:151
_render@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3419:57
render@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3415:151
render_receipt@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:348:1632
show@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:347:409
OdooClass.extend/</prototype[name]</<@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3538:488
show_screen@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:278:48
finalize_validation@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:370:349
validate_order@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:370:464
validate_order@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:487:71
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:3541:371
renderElement/<@http://localhost:8072/web/content/453-d9905cf/point_of_sale.assets.js:358:843
dispatch@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:892:451
add/elemData.handle@http://localhost:8072/web/content/424-bbeb3d6/web.assets_common.js:865:173

**Comment by Ramil-Mukhametzyanov** [comment]
@jwcaceres 
Hello, please use the debugger mode with assets to provide us with error logs
