### ISSUE TITLE
[pos_debt_notebook] Max Debt

### ISSUE THREAD

**Issue by jayo2005** [itpp-labs/pos-addons#1189]
Can we set max debt on the customer level? So one customer might be allowed credit of $1000. And another customer maybe $500. I can see there is a max level on the Journal but this is for all customers?

**Comment by Ramil-Mukhametzyanov** [comment]
Hello @jayo2005 
The maximum debt value can only be set for payment methods.
If you need different values for different customers, please contact our managers: pos@it-projects.info.
