### ISSUE TITLE
Any tips for the module Sale orders in POS

### ISSUE THREAD

**Issue by flotho** [itpp-labs/pos-addons#13]
Hi,

I'm wondering how your module "Sale orders in POS" works.
Is it possible to find a sale order and get it from the POS or is it the opposite way?
regards

**Comment by flotho** [comment]
Ok, the russian translation wasn't so obvious ;-)

I think I will collaborate with you on this with some improvements :
- take account of the owner of the sale order so that the pos.order will be associated to the sale.order as well
- Allow alpha numeric values as order number

Other tips for sure to come...

**Comment by yelizariev** [comment]
Hi,

Module "Sale orders in POS" allows to load product list by sale order id. So, it make pos order from sale order.

There is another module with the same tecnhincal name https://github.com/akretion/pos-sale-order/tree/master/pos_sale_order which make opposite -- it creates sale order from POS interface
