### ISSUE TITLE
Issue with pos_fiscal_floor

### ISSUE THREAD

**Issue by kkoci** [itpp-labs/pos-addons#140]
Hi, Whenever I try to access a table on my pos_restaurant

If I install pos_fiscal_floor, every click on a table will show me this error:

`too much recursion
http://localhost:8070/point_of_sale/static/src/js/db.js:153
Traceback:
PosDB<.save@http://localhost:8070/point_of_sale/static/src/js/db.js:153:49
PosDB<.save_unpaid_order@http://localhost:8070/point_of_sale/static/src/js/db.js:472:17
exports.Order<.save_to_db@http://localhost:8070/point_of_sale/static/src/js/models.js:1533:13
exports.Order<.initialize/<@http://localhost:8070/point_of_sale/static/src/js/models.js:1518:52
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35
triggerEvents@http://localhost:8070/web/static/lib/backbone/backbone.js:204:32
Backbone.Events.trigger@http://localhost:8070/web/static/lib/backbone/backbone.js:146:19
.update_summary@http://localhost:8070/pos_fiscal_floor/static/src/js/pos_fiscal_floor.js:18:17
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8070/web/static/src/js/framework/class.js:122:35

`

The error is about too much recursion, I guess is a javascript issue, but how can I solve this?

I'm using Odoov9 community compilation 20160712

BTW, I've downloaded the pos modules from 9.0 branch

Any ideas?

**Comment by yelizariev** [comment]
I think you haven't set default fiscal positions for floors

**Comment by yelizariev** [comment]
I've fixed this case. Thanks for report

**Comment by kkoci** [comment]
It is solved now, Thank You very much! спасибо
