### ISSUE TITLE
pos_multi_session odoo 13 stuck loading

### ISSUE THREAD

**Issue by nahe-consulting-group** [itpp-labs/pos-addons#1403]
pos_multi_session will you port it to odoo 13 ? i made some progress to port it but it's stuck loading. i would like to sponsor this port pos_multi_session_sync needs to work yoo with pos_multi_session 
How much would it cost? (i'm kinda broke but i can try get the money from a few potential clients) 
pos_multi_session works PERFECTLY in odoo 11 and 12 i just happend to need it for new proyect in odoo 13

**Comment by trojikman** [comment]
Hello,
we've received your e-mail and we will answer you after clarifying a couple of details.

Regards
