### ISSUE TITLE
[product_barcode_generator_custom] Usage

### ISSUE THREAD

**Issue by Ark74** [itpp-labs/pos-addons#148]
Hi!
I've been trying to figure this module out, but i can't get how it works.
I'm on Odoo v8.0 https://github.com/odoo/odoo/commit/c55c15aef39e9780cf48d2bc967b4e8357f31402

Used the latest **product_barcode_generator_custom** & **product_barcode_generator** (requirement) from github.
But no clue about the workflow with the addon.
Have somebody used it recently that could share their experience, maybe some change upstream broke something and that's why i can't see anything.

Thanks in advance for you attention :+1:

**Comment by yelizariev** [comment]
Check description here https://github.com/it-projects-llc/pos-addons/blob/9.0/product_barcode_generator_custom/__openerp__.py
