### ISSUE TITLE
tg_pos_pack to use with ecommerce??

### ISSUE THREAD

**Issue by frozseven** [itpp-labs/pos-addons#15]
Hi,

How can i use the tg_pos_packs to work with ecommerce? i want to add product packs for products/service and use it for ecommerce without POS. How can i use tg_pos_packs to do this? Please Help. Thank you

**Comment by yelizariev** [comment]
Hi,

you cannot. tg_pos_pack is for pos only

**Comment by frozseven** [comment]
Oh.. :( the module is really great in the POS... do u know how i could have product packs for products in ecommerce?

**Comment by yelizariev** [comment]
There is no module for that. You have to ask somebody to develop one
