### ISSUE TITLE
Problems with the POS module Available Stock

### ISSUE THREAD

**Issue by citruscorp** [itpp-labs/pos-addons#165]
In versions 9 and 10 does not work. I only work in some dependence python 8. Perhaps you needed? Permits?

**Comment by yelizariev** [comment]
Could you send screenshots of your issue? What goes wrong? What do you get and what do you expect?

**Comment by citruscorp** [comment]
No hay mucho que decir, instalo el módulo en las v9 y v10 pero el stock no
aparece en el POS, no hay cambios. En la v8 funciona sin problemas. Si me
mandas tu email privado te mando los accesos para que lo veas.

**Comment by yelizariev** [comment]
Ok, can you send screenshots:
- module record (form where you click "Install" and then see "Installed" label)
- screenshot of POS interface

Also, do you have other custom POS modules? Probably they are inconsistent and one override features of pos_product_available

**Comment by jayo2005** [comment]
Not working for me either on V10. No errors on install but when using POS the Available stock does not show.

**Comment by jayo2005** [comment]
Got it sorted, there was another module stopping it from working.
