### ISSUE TITLE
Customer Debt Undefined in TG POS Debt Notebook

### ISSUE THREAD

**Issue by ujaco** [itpp-labs/pos-addons#20]
When I create a new customer , his debt is undefined. When I try to make a debt sale for the same customer, then the amount becomes 0.0 not the amount of debt for the sale. 
![image](https://cloud.githubusercontent.com/assets/4730495/9837326/b188e834-5a58-11e5-9288-98c1289c9efc.png)

**Comment by yelizariev** [comment]
Thank you,
I'll fix it

**Comment by acaso** [comment]
Just to add more info, in case it helps…
Any subsequent debt sale for the same costumer does not change the debt shown in the POS, although the debt is indeed recorded (as you can see if you open the client form in the backend).
To show the correct debt amount in the POS, the POS has to be closed and open again OR just reloaded using the reload button of the web browser.
Once the correct amount is shown (after reloading the POS), it gets correctly updated on subsequent debt sales for the client.

**Comment by yelizariev** [comment]
@acaso thank you. @iledarn already works on this issue. It should be fixed soon
