### ISSUE TITLE
Blank Page Install the pos_enhanced module

### ISSUE THREAD

**Issue by rjay1018** [itpp-labs/pos-addons#23]
Hi @yelizariev , Page turns blank after i install the pos_enhanced for version module.  Please see the picture below.

![after i install the pos_enhanced](https://cloud.githubusercontent.com/assets/5526244/10473505/d20e4bb2-725e-11e5-8772-533f77955bb0.png)

Thank You

**Comment by yelizariev** [comment]
right, it doesn't work in 8.0
