### ISSUE TITLE
country field missing

### ISSUE THREAD

**Issue by mslokhat** [itpp-labs/pos-addons#25]
Hi,

trying to install on odoo 8.0 (latest nightly) , got this error :

Error details:
Field `country` does not exist

Error context:
View `view.tg.partner.tree`
[view_id: 826, xml_id: n/a, model: res.partner, parent_id: 124]" while parsing /usr/lib/python2.7/site-packages/openerp/addons/tg_partner_firstname/tg_partner_view.xml:30, near
<record model="ir.ui.view" id="view_tg_partner_tree">
            <field name="model">res.partner</field>
            <field name="name">view.tg.partner.tree</field>
            <field name="view_type">tree</field>
            <field name="inherit_id" ref="base.view_partner_tree"/>
            <field name="arch" type="xml">
                <data><field name="display_name" position="after">
                    <field name="firstname"/>
                    <field name="zip"/>
                </field>
                <field name="phone" position="after">
                    <field name="mobile"/>
                </field>
                <field name="email" position="after">  
                    <field name="country"/>
                </field>
            </data></field>
        </record>

**Comment by yelizariev** [comment]
Hi,

tg_partner_firstname is not ported for 8.0 as I don't use it myself and don't have a sponsor to fix it

**Comment by mslokhat** [comment]
Hi,

ok, forget it, 
i'm using odoo v9, and would like to sponsor some features (ex : multisession)
please contact me.

**Comment by yelizariev** [comment]
@mslokhat email me to yelizariev@it-projects.info

**Comment by yelizariev** [comment]
County field issue was fixed https://github.com/it-projects-llc/pos-addons/commit/eafe18ef05a0c051853806081eb2dbdb433c9eee
