### ISSUE TITLE
Syncing problems during order splitting creates duplicate items

### ISSUE THREAD

**Issue by multiwebinc** [itpp-labs/pos-addons#268]
I have Sync POS orders across multiple sessions and Sync restaurant orders installed. Here is an example:

- Connect POS1 and POS2
- On POS1 add an order with multiple items
- On POS1 click on split and add a few items to be split, but then click "Back"

Result:

On both POSes the original order remains unmodified, however on POS2 a new order is created with the items before the "Back" button were pushed. The items are therefore duplicated. I would expect it to not create a new order until the order is actually split.

**Comment by cvinh** [comment]
Fixed here https://github.com/it-projects-llc/pos-addons/pull/324
