### ISSUE TITLE
Unit Tests for pos_disable_payment [$40 awarded]

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/pos-addons#273]
We are looking for someone who can write  [unit tests](https://www.odoo.com/documentation/8.0/reference/testing.html) for the [module](https://github.com/it-projects-llc/pos-addons/tree/10.0/pos_disable_payment)

The tests has to check for each feature below, that it works without disabling and doesn't work with disabling. Only 10.0 branch is required.

> Disable payments
> Disable removing non-empty order
> Disable discount button
> Disable edit price button
> Disable decrease order line
> Disable removing order line

This is the first issue to try bouncing system.

Some information on writing test can be found here:
* https://odoo-development.readthedocs.io/en/latest/qa/index.html
* https://github.com/it-projects-llc/pos-addons/blob/10.0/pos_multi_session/external_tests/tests/inject.js (not a *automatic* tests, but contains useful code)

**Comment by yelizariev** [comment]
Bounty is 40$ now

**Comment by yelizariev** [comment]
ping

**Comment by ghost** [comment]
Hi. I'm interested in creating tests for this pos_disable_payment and already I've cloned the repo.
But I'm stuck where I try to import **odoo** python dependency, because I get errors messages when I try to run the tests.

Can I get some help to get this issue done?

**Comment by yelizariev** [comment]
Well, you need to install odoo first.
Try Doodba https://github.com/Tecnativa/doodba/blob/master/README.md#run-unit-tests-for-some-addon
or official docs: 

* https://www.odoo.com/documentation/13.0/setup/install.html
* https://www.odoo.com/documentation/13.0/reference/testing.html

**Comment by ghost** [comment]
Well, I already installed on my environment, but I'll check those links that you wrote above.
Any news I will let you know.
Thanks in advance.
