### ISSUE TITLE
[9.0][10.0] problem to inherit push_order

### ISSUE THREAD

**Issue by gaelTorrecillas** [itpp-labs/pos-addons#281]
hello, 

in our inheritance of push_order, we lose the options.

https://github.com/it-projects-llc/pos-addons/blob/10.0/pos_product_available/static/src/js/pos.js#L26

fix in commit : https://github.com/MindAndGo/pos-addons/commit/3697a71b443c9dcd627c039c4caa1b6e0db030e6

**Comment by yelizariev** [comment]
Hello, 
thank you for update

@ilmir-k, check and apply this commiit please
