### ISSUE TITLE
Restaurant : Error Tables 

### ISSUE THREAD

**Issue by mslokhat** [itpp-labs/pos-addons#29]
![image](https://cloud.githubusercontent.com/assets/8535048/11110062/e20e1e66-8910-11e5-8762-c0f377d931d1.png)

![image](https://cloud.githubusercontent.com/assets/8535048/11110071/f98e6d84-8910-11e5-9979-ae6bb3613c63.png)

the system is buggy
tables are not sync :
1. on floor plane . waiters have different views , noone can know which is good or not
2. demo has created an order on table T3  (ticket 10) , while administrator sees it in table T2 (ticket 10)
3. if administrator select a table (T3) , a new order is created (ticket 12)

requests :
1. sync the floors so that all waiters see the same informations
2. if a ticket has been opened by a waiter, do not create a new ticket but use the existing one 
3. restrictions (disable payment, remove line, price,...) should be on user level, not on pos level
ie : if the cashier logs to the pos, he should be able to take payment,change price, ...

Thanks

**Comment by yelizariev** [comment]
modules were tested only for case with one restaurant POS and multiple non-restaurant POS.

Wait for news or contact me to sponsor updates.

**Comment by mslokhat** [comment]
what do you mean by non restaurant pos? maybe i do not understand how it works.

**Comment by yelizariev** [comment]
At Point of Sale/Configuration/Point of Sale you can create new POS without restaurant floors. Such POS works as usual (non-restaurant) POS. Then each user login to related POS.

**Comment by yelizariev** [comment]
> restrictions (disable payment, remove line, price,...) should be on user level, not on pos level
> ie : if the cashier logs to the pos, he should be able to take payment,change price, ...

I prefer to keep current design, because anyway there should be different POS for each user, e.g. POS-cacher, POS-waiter1, POS-waiter2 etc. But I can create new modules that will allow to specify which users has access to login to particular POS

**Comment by mslokhat** [comment]
restrictions (disable payment, remove line, price,...) should be on user level :

imagine a waiter taking order on a pos (either tablet or computer), the cashier can login on this device (pos -> change cashier , ie click on user and select another one) 
and then do the sale

this is valid for a supermarket where a manager can remove a line ,...

**Comment by yelizariev** [comment]
ok, I got it.

Another question. Do you have multiple POS? If so, how do you configure floors on different POSes? As I understand each POS has own floors?

**Comment by mslokhat** [comment]
oups, i have the shared floors and tables module. will send you

**Comment by yelizariev** [comment]
Shall I publish it in my repo?

**Comment by yelizariev** [comment]
Or it have been published somewhere else already?

**Comment by mslokhat** [comment]
hi. this is a private work and paid a dev for it. what do you think?

**Comment by yelizariev** [comment]
It has a AGPL licence, so you (and even me) has a right to publish it.
Anyway I'd like to keep pos_multi_session_restaurant opensource and hence all dependencies should be opensource too.

**Comment by mslokhat** [comment]
ok. you can  publish on your repo but keep my name as author/sponsor. thanks

**Comment by yelizariev** [comment]
sure.
It has

```
'author' : 'T.V.T Marine Automation (aka TVTMA)',
'website': 'http://ma.tvtmarine.com',
```

as a name now.  Shall I update it?

Also, it has AGPL license now, which force me to switch my modules from LGPL to AGPL. Do you have a right to relicense it to LGPL? Would you like to do it?

**Comment by mslokhat** [comment]
tvt marine was the dev i hire to do it. i don't know if we can do it. i do
not care much.

sure.
It has

'author' : 'T.V.T Marine Automation (aka TVTMA)',
'website': 'http://ma.tvtmarine.com',

as a name now. Shall I update it?

Also, it has AGPL license now, which force me to switch my modules from
LGPL to AGPL. Do you have a right to relicense it to LGPL? Would you like
to do it?

**Comment by yelizariev** [comment]
done https://github.com/yelizariev/pos-addons/tree/9.0/to_pos_shared_floor

**Comment by yelizariev** [comment]
Done in #36
