### ISSUE TITLE
Notebook Debt Initial Debt [$300 awarded]

### ISSUE THREAD

**Issue by jclopezar** [itpp-labs/pos-addons#297]
# Question : Initial debt
Is there any method to load previos customer debts at install time?.
Workaround:  
Define a product to register previos debt and create the initial debt, all do a bit painfully if there are more than 400 customer with debts.

👍

**Comment by yelizariev** [comment]
Hi,
that is a good question.
I think we can add a table for *manual debt changes* and add it in debt computations.
The same solution could be used for other purposes, e.g. clean up test Credits and other.

Not sure when I can do that, though.

**Comment by jclopezar** [comment]
Hi,
I thought about the same solution,mainly  to recover some history.
If you agree, next week I'll do a PR with a basic solution: (model to load history and include the table in the view).
Let you know when it's ready

**Comment by yelizariev** [comment]
yes, sure. You are welcome to contribute

**Comment by gustavovalverde** [comment]
Just relating things. 
Will also help me with https://github.com/it-projects-llc/pos-addons/issues/332
