### ISSUE TITLE
POS Debt Notebook in Offline Mode

### ISSUE THREAD

**Issue by novatorapps** [itpp-labs/pos-addons#307]
When the POS goes offline with POS Debt Notebook module installed on V10 (community), 'loading' flashes on pos. See this: https://www.dropbox.com/s/xkjt98g9yku4vp0/Screenshot%202017-06-05%2011.34.13.png?dl=0

Once offline, the POS shows errors in developer console. New error appears every second. See here: https://www.dropbox.com/s/dcl0bb8cfzs07j4/Screenshot%202017-06-05%2011.35.09.png?dl=0

Is this behavior normal? Thanks

**Comment by yelizariev** [comment]
Yes, it's correct behavior that allows to knows that something wrong with connection. I don't think that we need to change anything here.

**Comment by novatorapps** [comment]
Thanks!
