### ISSUE TITLE
[10.0-pos_multi_session] Changing fiscal position in pos_order does not sync

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#318]
Steps to reproduce : 
- set up 2 fiscal position with tax mapping
- open 2 sync sessions and add items
- on session 1, change fiscal position
Actual behavior : 
- the taxes do not sync
Expected behavior : 
- the taxes should sync

**Comment by KolushovAlexandr** [comment]
done in 318 pr

**Comment by yelizariev** [comment]
#318

**Comment by yelizariev** [comment]
@KolushovAlexandr where?

**Comment by KolushovAlexandr** [comment]
@yelizariev https://github.com/it-projects-llc/pos-addons/commit/d7e2db69fa2dc80d47f3ee7fc69dd33bf60858f0#diff-ad2bbea675bb6487d11f74ed261a92f6

**Comment by yelizariev** [comment]
Ok, so the PR num is https://github.com/it-projects-llc/pos-addons/pull/467
