### ISSUE TITLE
[10.0-pos_multi_session_restaurant] kitchen printer state does not sync on table floor screen

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#319]
Steps to reproduce : 
- set up a kitchen printer in 2 pos belonging to the same multisession
- add items on a table that need to be printed in kitchen but do not press the order button
Actual behavior : 
- on the other pos, on the table floor, the order stays black --> we need to go on other floor and come back to see it's red
Expected behavior : 
- on the other pos, on the table floor, the order must be red without having to go on other floor and come back

**Comment by Englishrain** [comment]
Confirmed
