### ISSUE TITLE
tb_pos_packs: Pack Checkbox and Pack Tab disappear forever when POS-Product Category is deleted

### ISSUE THREAD

**Issue by treviser** [itpp-labs/pos-addons#32]
I'm really impressed by this module. However, I deleted the POS product category "Custom Packs" because I don't need such a category on my POS display and now I can not create new packs because the checkbox and the tab disappeared. Already defined packs do still work.

**Comment by yelizariev** [comment]
@treviser 
the module was made by another person. "Custom Packs" is hardcoded  https://github.com/yelizariev/pos-addons/blob/9.0/tg_pos_packs/tg_pos_product_pack.py#L68
I didn't make changes there, but it could be fixed
