### ISSUE TITLE
[10.0-pos_multi_session_restaurant] Split table in one pos changes kitchen printer state on other pos

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#320]
Steps to reproduce :
- set up a kitchen printer in 2 pos belonging to the same multisession
- add items on a table that need to be printed in kitchen and process the order
- on the other pos, press divide button, select some items and process payment
Actual behavior : 
- on the first pos, on the floor screen, the table has red spot but nothing to send to the kitchen printer
Expected behavior : 
- as no change has been made on the pos_order, the table should have black spot on the floor screen

**Comment by Englishrain** [comment]
Confirmed
