### ISSUE TITLE
[10.0-pos_multi_session] exception error for pos that does not belong to multisession

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#322]
Steps to reproduce : 
- setup a pos that does not belong to multisession (ie. let the multisession field empty)
- open the pos

Actuel behavior : 
`TypeError: multi_session_update() takes exactly 3 arguments (2 given)\n","exception_type":"internal_error","message":"multi_session_update() takes exactly 3 arguments (2 given)","name":"exceptions.TypeError","arguments":["multi_session_update() takes exactly 3 arguments (2 given)"]}}`

**Comment by Englishrain** [comment]
Сonfirmed

**Comment by yelizariev** [comment]
Fixed in https://github.com/it-projects-llc/pos-addons/commit/595f894aa9e18b5a6d4ea6e24e71563f4a942549
