### ISSUE TITLE
[10.0-pos_multi_session] Creating new customer in one pos makes a error in other pos

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#327]
Steps to reproduce : 
- setup 2 poses belonging to the same multi_session
- on first pos, create a new order
- create a new customer and select it
Actual behavior : 
- on second pos, we have "ReferenceError: Can't find variable: Model"
Expected behavior : 
- no error and customer is synced in second pos

**Comment by Englishrain** [comment]
confirmed

**Comment by yelizariev** [comment]
@invitu it was fixed by @KolushovAlexandr 
check latest version
