### ISSUE TITLE
Need fixed or add more option for multi restaurant sync section [$15 awarded]

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#328]
The current one workflow like:
the client comes to (Table 1) ask for the order
The first waiter come and take order -> it print to kitchen
client in (Table 1) ask for order more
second order come and take the order - > system cancel all the old order and preprint again all old & new order (it make me confuse even I work from tourism before)
so the simple way is:
the client comes to the restaurant table
The first waiter come & take the order -> print to kitchen
client ask to order more
second order come & take the order -> printing just new order to the kitchen
That all

**Comment by yelizariev** [comment]
Clarify please what kind of options should be added?

**Comment by 360org** [comment]
i have submit but it gone away. let me do it again

**Comment by 360org** [comment]
The current one workflow like: 
client come to (table 1) ask for order
first waiter come and take order -> it print to kitchen
client in (table 1) ask for order more 
second order come and take order - > system cancel all the old order and preprint again all old & new order (it make me confuse even i work from tourism before)
so the simple way is:
client come to restaurant table 
first waiter come & take order -> print to kitchen
client ask order more
second order come & take order -> printing just new order to kitchen
That all

**Comment by 360org** [comment]
i can sponsor 40$ if you fixed that in quick. plz sent me payment info

**Comment by 360org** [comment]
Hello i have limit paypal account do you have other payment method?

**Comment by 360org** [comment]
it ask payment here: https://www.bountysource.com/issues/46833053-need-fixed-or-add-more-option-for-multi-restaurant-sync-section?utm_campaign=plugin&utm_content=tracker%2F2289114&utm_medium=issues&utm_source=github
but i dont have paypal & bitcoin

**Comment by cvinh** [comment]
@W360S @yelizariev Hello I confirm the issue : 
- waiter1 add items for table1 and print kitchen ticket
- waiter2 adds new items for table1 and print kitchen ticket
Actual Behavior : 
- the second ticket prints "cancelled" first items and "new" first items + second items
Expected Behavior : 
- the second ticket should print only "new" second items

**Comment by yelizariev** [comment]
Is it for odoo.10?

**Comment by 360org** [comment]
Yeap im running v10

**Comment by yelizariev** [comment]
@W360S It should be fixed now. Try latest version.
Thank you for contribution

**Comment by yelizariev** [comment]
@invitu you are welcome to try latest version too

**Comment by 360org** [comment]
yeap thanks for your help :) do you have other payment method? as i said i can sponsor for this :)

**Comment by yelizariev** [comment]
@W360S contact us at it@it-projects.info

**Comment by 360org** [comment]
ok sure
