### ISSUE TITLE
Multi section error [$75 awarded]

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#330]
Hello i have error with multi section error plz help i can pay for that. plz fixed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/en-addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/en-addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/en-addons/point_of_sale/models/pos_order.py", line 510, in create_from_ui
    pos_order = self._process_order(order)
  File "/home/odoo/pos-addons/pos_order_cancel/models/models.py", line 32, in _process_order
    order = super(PosOrder, self)._process_order(pos_order)
  File "/home/odoo/en-addons/point_of_sale/models/pos_order.py", line 117, in _process_order
    if pos_session.sequence_number <= pos_order['sequence_number']:
KeyError: 'sequence_number'

**Comment by multiwebinc** [comment]
I am also having this issue with almost exactly the same text. Everything was working perfectly for several months, but as of 1 week ago, I now get the following error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo10/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo10/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo10/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo10/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo10/addons/point_of_sale/models/pos_order.py", line 548, in create_from_ui
    pos_order = self._process_order(order)
  File "/opt/odoo/odoo10/addons/point_of_sale/models/pos_order.py", line 117, in _process_order
    if pos_session.sequence_number <= pos_order['sequence_number']:
KeyError: 'sequence_number'
```

Orders do not get saved. A bill is printed, you can submit payments on the orders, but when the staff members close their sessions at the end of the shift, balances are all zero. POS shows 195 warnings. Console contains:

```
Failed to send orders: Array(195)
```

which appears to contain all of the orders that have been entered, but have not been saved to the server.

LocalStorage also appears to have a variable with the name ending with "unpaid_orders", which I believe has the same information in JSON format:

Download txt file: [localstorage_unpaid_orders.json.txt](https://github.com/it-projects-llc/pos-addons/files/1201927/localstorage_unpaid_orders.json.txt).

**Comment by multiwebinc** [comment]
If it makes any difference, my Installed IT-Projects modules are:

* To POS Shared Floor
* Disable payments in POS
* POS Longpolling
* Sync POS orders across multiple sessions
* Sync restaurant orders

**Comment by 360org** [comment]
Hello @multiwebinc can you sponsor a little to make it done? me and you 50/50 :)

**Comment by multiwebinc** [comment]
@W360S If you would like to add a bounty, feel free to add any amount you wish. If the IT-Projects team feels it's not enough to make them interested, we can talk about increasing our bounties or hopefully getting others donating too. However in my experience in programming, exception errors usually have very simple fixes. Often just finding what is causing the error takes significantly more than coding the fix.

**Comment by 360org** [comment]
yeap i know that but to make it quick :) we can sponsor little bit :) 50$ can fixed the error. can you sponsor for 25$? i do same too :)

**Comment by multiwebinc** [comment]
@W360S I already added a $50 bounty.

**Comment by 360org** [comment]
:) thanks i will do little bit :)

**Comment by 360org** [comment]
Arady did :)
![2017-08-05 09-03-19 paypal checkout - payment completed](https://user-images.githubusercontent.com/8590556/28992070-2654e05c-79bd-11e7-985d-01c6fee90465.png)

**Comment by 360org** [comment]
Hello @yelizariev can we do fixed it in quick?

**Comment by yelizariev** [comment]
@W360S, hopefully @GabbasovDinar will fix it this weekend

**Comment by 360org** [comment]
:) thanks

**Comment by GabbasovDinar** [comment]
Hello all,
Thanks for bounti!
I started to solve this issue

**Comment by GabbasovDinar** [comment]
We can not reproduce this error but found theoretical reason, I will send PR soon

**Comment by 360org** [comment]
In multi section sometimes have an error like above it happens when has broken Wi-Fi connect or some device cannot connect to printing then it freezing the whole system and show that error.
The way temporally to fixed that stops all device clear all browser cache and start again but all the data will be lost.

**Comment by 360org** [comment]
sometimes waiter sent the order request to the kitchen but the button order still green and system show that error like above.
the current solution we need to take another device submit the request and clear all history data in the error device and it works again.

**Comment by 360org** [comment]
sometimes it prints the double bill because it still printing each time submit order but system not accept  the request, order button still green

**Comment by 360org** [comment]
and it happens when you have a lot of requests.
if the restaurant has normal client it still ok. but when increase guest come to the restaurant and we do submit a lot of requests and it happens.

**Comment by multiwebinc** [comment]
@GabbasovDinar @yelizariev Assuming the commit fixes the error, will that add any of the past orders saved in local storage? If so, will they appear with the correct dates, or with the date of the first new session after the fix is applied? Or will they be lost?

**Comment by multiwebinc** [comment]
I finally got around to trying the fix and it did not fix the error for me. I now have over 400 unpaid orders that are not syncing to the server. However when I log in with that user on another computer (obviously with a different local storage), I am able to successfully post orders without any error. I would assume that I need to somehow sync the local storage with the server. That's what seems to be broken here for me. Is there any way to at least manually go through them and add a new order? I know it would be tedious, but we need to get things working properly. I'm not even able to calculate the taxes we owe or the gratuities I need to pay to the staff.

**Comment by multiwebinc** [comment]
OK, doing some more tests, when I copy the local storage from the computer with the error to another computer, the other computer then also displays the sync errors as well. However going through the local storage variables, the `openerp_pos_db_e7016812-673e-4b5c-b230-883127864c4f_orders` and `openerp_pos_db_e7016812-673e-4b5c-b230-883127864c4f_unpaid_orders` both have 117 items in each. It looks as if they have the same items. However checking the JS console, I get a completely different list of orders not syncing. It says it's an array with 485 items. I also checked and the IDs are different from the ones in local storage as well. The above two variables are the only two large variables in the local storage, so the weird question is, where are the unregistered orders saved?

Also of interest, some of the orders (maybe about 30 of the 485) have IDs like: `00425-001-0NaN`.

**Comment by pedroslopez** [comment]
We use the multi_session module and were having an issue with the sequence_number as well. Basically, since one order for some reason lost its sequence_number, all the other orders are held back because of the way the queue works (waiting for the first one to successfully send to server).

We fixed it temporarily by giving the first order up a sequence number, and then all of the orders were able to be sent to the server.

So, we did some investigating to see why the sequence_numbers were randomly disappearing (it happened multiple times) and we found a solution.

The function `do_ms_update()` expects the response of the update to be successful, with an "update_revision_ID" action that contains the order_ID and revisionID parameters. The problem occurs when this response is NOT an update_revision_ID, but rather a revision_error. This response does NOT contain the required order_ID and revision_ID parameters, so when it tries to do `self.sequence_number = order_ID`, it sets it as undefined.

We were able to fix the issue by changing the if statement from `if(res)` to `if(res && res.action=="update_revision_ID")`, so we only run that code if the action is as expected. (#355)

Just a note, we fixed this on the 9.0 branch, but it seems to be the same issue. Also, while this will fix this from happening again, it will not fix the orders that currently have the issue.

**Comment by multiwebinc** [comment]
@pedroslopez Thanks for the explanation. Is there any way to manually add a sequence_number to the ones that are incorrect so that they can all be synced?

**Comment by yelizariev** [comment]
@pedroslopez 

> The function do_ms_update() expects the response of the update to be successful, with an "update_revision_ID" action that contains the order_ID and revisionID parameters. The problem occurs when this response is NOT an update_revision_ID, but rather a revision_error. This response does NOT contain the required order_ID and revision_ID parameters, so when it tries to do self.sequence_number = order_ID, it sets it as undefined.

We made the same conclusion and fixed it here: https://github.com/it-projects-llc/pos-addons/commit/a3a8685143a0e0cdc107a2a57aeedf5899460053 You probably didn't see that updates

**Comment by yelizariev** [comment]
@multiwebinc You can try to modify localStorage manually via Developers tools (F12 in Chrome). After that reload POS. Be carefull about it and make backup of localStorage before changing it. Also, I suggest to do it on backup of database first

**Comment by pedroslopez** [comment]
@yelizariev This does fix the issue when it occurs when removing an order, but not when a revision_error is returned on set_order

**Comment by yelizariev** [comment]
@pedroslopez I understand your point. It seems to be right. We will check it

**Comment by yelizariev** [comment]
@pedroslopez What we think is that this update https://github.com/it-projects-llc/pos-addons/commit/a3a8685143a0e0cdc107a2a57aeedf5899460053#diff-ec4abf1b4d0139dc7e10154d4a34c2d3R381 is enough and prevents from setting wrong value to sequence_number in both cases (removing order and revision_error)

But I can say that your solution is essential only when there is no that updates. Thanks for your analyzing and PR anyway. It makes us assure that we are on right way.

I have merged your PR to remove any doubts. 

Thanks to all!

@multiwebinc let me know when you resolve issue with localStorage to close this issue

**Comment by 360org** [comment]
Hello @yelizariev 
I have found security hole bug that staff can cheat in pos.
The situation is:
1 water going to order 3 pizza and submit order to the kitchen (It work fine for normal workflow)
and the restaurant serves the client as normal.
and guest going to pay for the bill (Water ask for payment total 3 pizza) it is ok, guest leave.
but the problems are: the water deleted 2 of the pizza billing and check out the table.
the pos system has no notified or any cancel in the posted in the system

so the way to fixed that is:
the water can cancel (deleted order) but when he/she try to take payment (check out table) the system pop up notifies that order has been changed if they say yes, order cancel will be printed in the kitchen and posted to the system.
if they say no so they have to correct the order number and take payment.
Can you help for that?

**Comment by yelizariev** [comment]
@W360S please make a separate issue for that. Short answer here: we are going to save at backend all canceled (removed) orders\order lines with information who canceled it

**Comment by 360org** [comment]
ok thanks i will make it separate :)

**Comment by multiwebinc** [comment]
I don't have time to test it right now. Feel free to close this ticket and if I do run into issues in the future I will either reopen this (if I can) or submit a new issue.

**Comment by 360org** [comment]
Hello, the error come today.
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
return self.method(*args, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
response = f(*args, **kw)
File "/home/odoo/en-addons/web/controllers/main.py", line 862, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/home/odoo/en-addons/web/controllers/main.py", line 854, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 687, in call_kw
return call_kw_model(method, model, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_model
result = method(recs, *args, **kwargs)
File "/home/odoo/en-addons/pos_loyalty/models/pos_order.py", line 20, in create_from_ui
order_ids = super(PosOrder, self).create_from_ui(orders)
File "/home/odoo/en-addons/point_of_sale/models/pos_order.py", line 510, in create_from_ui
pos_order = self._process_order(order)
File "/home/odoo/pos-addons/pos_order_cancel/models/models.py", line 34, in _process_order
order.cancellation_reason = pos_order['CancellationReason'].encode('utf-8').strip(" \t
")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 26: ordinal not in range(128)
plz help

**Comment by 360org** [comment]
![1503989304594_11468](https://user-images.githubusercontent.com/8590556/29808234-6f48cb86-8cc1-11e7-8485-55b3b5f1ff79.jpg)
![1503989187858_11463](https://user-images.githubusercontent.com/8590556/29808251-7d5a4eac-8cc1-11e7-9662-9d06464b7e2a.jpg)
here is the next error message
