### ISSUE TITLE
Error double printing

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#331]
Heloo i have error double prtinting plz help!![](http://i.imgur.com/XzWX2gF.jpg)

**Comment by yelizariev** [comment]
@GabbasovDinar did you face anything similar?

**Comment by GabbasovDinar** [comment]
@yelizariev no, but I can fix this problem later. How to get this error?

**Comment by 360org** [comment]
there are sometimes order submit it print and later about few minutes it comes again with the same order and same time but nobody submits.

**Comment by 360org** [comment]
fixed in #330
