### ISSUE TITLE
[pos_debt_notebook] Initial balance for Purchased Credits (In)

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#333]
It'd be useful if the initial balance for the `Purchased Credits (In)` could be uploaded using csv or if it could be predefined somehow, as this options just gets affected by buying a credit product, but what if I'm receiving this information from an old system or an external user?

**Comment by yelizariev** [comment]
I think [manual debt updates](https://github.com/it-projects-llc/pos-addons/issues/297#issuecomment-299839102) will cover your need, will not it? It can be used for initial balance as well as recurring updates. Is that what you are asking for?

**Comment by gustavovalverde** [comment]
Closing. Is actually the same as: https://github.com/it-projects-llc/pos-addons/issues/297
