### ISSUE TITLE
POS debt notebook bug

### ISSUE THREAD

**Issue by jayo2005** [itpp-labs/pos-addons#342]
Odoo 10
Hi I seem to have found a bug in the POS debt notebook module. From the main POS if you add item Pay Debt which is €0.00 and click payment. Then click on pay full debt it doubles the payment amount. See image below. As you can see the debt is 38.75 but for some reason it adds two debts. 

![2017-07-29_11-10-40](https://user-images.githubusercontent.com/7015925/28743994-7798e666-744f-11e7-8ffe-a522d0cd23e0.png)

**Comment by yelizariev** [comment]
We confirm the issue. Kindly wait for updates

**Comment by soulimane-mammar** [comment]
Hi,
I confirm the bug and there is another issue
When a user wants to pay his debts and give more cash than the amount of the debt, the message "please enter the exact or lower debt amount than the cost of the order ..." appears
![image](https://user-images.githubusercontent.com/18255717/29479877-9d5729a8-846c-11e7-8610-89c246f52ce8.png)
 
![image](https://user-images.githubusercontent.com/18255717/29479915-c55d8a6e-846c-11e7-8233-40cf5439003d.png)

**Comment by soulimane-mammar** [comment]
To fix the problem I just added an else statement, I don't know if it's OK !!!

screens.PaymentScreenWidget.include({
        validate_order: function(options) {
            var currentOrder = this.pos.get_order();
            var isDebt = false;
            var plines = currentOrder.get_paymentlines();
            var debt_amount = 0;
            for (var i = 0; i < plines.length; i++) {
                if (plines[i].cashregister.journal.debt) {
                    isDebt = true;
                    debt_amount += plines[i].amount;
                **}else { 
                    isDebt = false;
                }**
            }

**Comment by soulimane-mammar** [comment]
The last fix is for 9.0

**Comment by soulimane-mammar** [comment]
in 10.0 this portion of code is doing the test on the whole order and it shoud be just for the line payment that is marked as debt...I think so

```
if (isDebt && currentOrder.get_total_paid() > currentOrder.get_total_with_tax()) {
                this.gui.show_popup('error', {
                    'title': _t('Unable to return the change with a debt payment method'),
                    'body': _t('Please enter the exact or lower debt amount than the cost of the order.')
                });
                return;
            }

```

**Comment by soulimane-mammar** [comment]
The idea is to ensure that Debt payment lines are ok (amount <= due) so I commented this portion of code
```
/* if (isDebt && currentOrder.get_total_paid() > currentOrder.get_total_with_tax()) {
                this.gui.show_popup('error', {
                    'title': _t('Unable to return the change with a debt payment method'),
                    'body': _t('Please enter the exact or lower debt amount than the cost of the order.')
                });
                return;
            }*/
```

and  inserted this portion to ensure that debt payment line are ok

            if (!currentOrder.isDebt_payment_lines_OK()) {
                this.gui.show_popup('error', {
                    'title': _t('Unable to return the change with a debt payment method'),
                    'body': _t('Please enter the exact or lower debt amount than the cost of the order.')
                });
               return ;
            }

The implementation of `isDebt_payment_lines_OK` is as follows:
```
isDebt_payment_lines_OK: function() {
            var currentOrder = this.pos.get_order();
            return this.paymentlines.every(function(line){
                    if (line.cashregister.journal.debt)
                        return line.get_amount() <= currentOrder.get_due(line);
                    else return true ;
                });

        }
```

**Comment by soulimane-mammar** [comment]
Hi,
For the first bug exposed by jayo2005 the fix is to replace in pos.js file  
 `  $pay_full_debt.on('click', function() { `
by
` $pay_full_debt.off().on('click', function() { `

There are still other bugs that I discovered.... see you in next posts
