### ISSUE TITLE
security hole bug that staff can cheat in pos

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#363]
Hello @yelizariev
I have found security hole bug that staff can cheat in pos.
The situation is:
1 water going to order 3 pizza and submit order to the kitchen (It work fine for normal workflow)
and the restaurant serves the client as normal.
and guest going to pay for the bill (Water ask for payment total 3 pizza) it is ok, guest leave.
but the problems are: the water deleted 2 of the pizza billing and check out the table.
the pos system has no notified or any cancel in the posted in the system

so the way to fixed that is:
the water can cancel (deleted order) but when he/she try to take payment (check out table) the system pop up notifies that order has been changed if they say yes, order cancel will be printed in the kitchen and posted to the system.
if they say no so they have to correct the order number and take payment.
Can you help for that?

**Comment by yelizariev** [comment]
Check this: https://github.com/it-projects-llc/pos-addons/pull/389
it saves all removing at backend, but it doesn't print cancelation automatically. 
We consider it as interesting option and could add it option if someone sponsor it.

**Comment by 360org** [comment]
Hello! that fine but the currently it does not save in my system what can I do?
I have updated the latest code. do I need to do any extra step?

**Comment by yelizariev** [comment]
@W360S 
I was not merged to this repo until today. Try again.

**Comment by 360org** [comment]
do i have to install any extra module? @yelizariev

**Comment by yelizariev** [comment]
You need to install pos_order_cancel_restaurant

**Comment by 360org** [comment]
i try to install that module but a lot of error. 
whole system fails not sign with multi section

**Comment by yelizariev** [comment]
I forgot to say, that you also need to install this module: pos_multi_session_restaurant_cancel_order

**Comment by 360org** [comment]
it breaks my system now, show error when im trying to login pos section.
here is the error: #381
