### ISSUE TITLE
[10.0 - POS Debt Notebook]: Manual updates won't reset credit_balance on partner [$300 awarded]

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#367]
When using Manual Updates, I'd expect that the `credit_balance` used in the partner is also set to the same amount of the last update, but it's not, it just adds up every Manual Update done in the past to the last one.

**Comment by yelizariev** [comment]
Yes, I made it to work this way. Manual update adds value instead of setting new value. What we can do here to try to improve UX is to add new field "New Balance" and compute "Balance Update" depending on "New Balance" and  "current credit_balance"

**Comment by gustavovalverde** [comment]
Agree

**Comment by yelizariev** [comment]
Clarification for one who will do it: 
"Balance Update" must NOT be changed (recomputed) if state is  "confirmed".

**Comment by ghost** [comment]
@yelizariev Working on it: https://github.com/it-projects-llc/pos-addons/pull/396 Please review, when you'll have a time. Thank you!
