### ISSUE TITLE
[ 10.0-20170814 POS ] Can not close POS session cause of account 

### ISSUE THREAD

**Issue by ghost** [itpp-labs/pos-addons#370]
I created a new POS with Cash control but I can not close it, It always shows a warning like this: 
`You cannot use this general account in this journal, check the tab 'Entry Controls' on the related journal.`
I'm using Cash as Payment method
I tried to disable Cash Control but still can not close it
Please show me the way!

**Comment by yelizariev** [comment]
Do you think that some of our modules leads to this problem?
