### ISSUE TITLE
[10.0 - pos_longpoll] Adding new table doesn't sync real-time

### ISSUE THREAD

**Issue by toeh101** [itpp-labs/pos-addons#375]
Open table page in POS restaurant mode on two windows. 
Add one table on a window. The recent added table doesn't appear in another window until I refresh it.
Thank you.

**Comment by yelizariev** [comment]
Hi @toeh101 
we don't consider this as a bug. Table adding is not something you need to do every day. You can setup it once and just restart POS (refresh page). 
But I see a problem here, that user may expect that tables are synced too. We consider it as low priority. One can sponsor it via bounty to encourage development
