### ISSUE TITLE
shared sessions and tables : Reference error

### ISSUE THREAD

**Issue by mslokhat** [itpp-labs/pos-addons#38]
Hi,

i'm testing latest code 

i got this on a new DB : 

![image](https://cloud.githubusercontent.com/assets/8535048/11720737/0ab33624-9f7a-11e5-90f2-f1940b18e6d5.png)

**Comment by mslokhat** [comment]
the error is in pos_multi_session.js : line 114 :

ms_on_update: function(message){
            this.ms_syncing_in_progress = true; // don't broadcast updates made from this message
            var error = false;
            try{
                console.log('on_update', message)
                var action = message.action;
                var data = message.data || {}
                var order = false;
                if (data.uid){
                    order = this.get('orders').find(function(order){
                                return order.uid == data.uid;
                            })
                }
                if (order && action == 'remove_order'){
                    order.destroy({'reason': 'abandon'})
                } else if (action == 'update') {
                    this.ms_do_update(order, data);
                }
            }catch(err){
                error = err;
                console.error(err);
            }

**Comment by yelizariev** [comment]
@ilyasProgrammer

**Comment by yelizariev** [comment]
Fixed
