### ISSUE TITLE
[pos_multi_session] Orders being created with same UIDs

### ISSUE THREAD

**Issue by pedroslopez** [itpp-labs/pos-addons#383]
Hello,

We have been receiving reports of orders that have been printed and everything not being synced to other terminals and disappearing on refresh. Investigating the issue, I found the root cause of the issue was that the order having the sync problems actually had assigned the same UID as another order. Some more details follow:

(To clarify OLD/ORIGINAL order is the one that first had the UID assigned, NEW/CURRENT order is the one that was just created and is having issues)

1. They were created in the same POS terminal
2. Modifying the new order gave revision_errors, as the revision_id of the current order is 1, but the order on the server was higher.
3. sync_all apparently didn't resolve the issue because the old order was still active in the POS, so when it tries to sync_all, it finds the original order.

Trying to resolve this, we found this to be reproducible doing the following steps:
1. Turn OFF connection to the server
2. Create new order and add a couple items to it. Take note of its UID.
3. Turn ON connection to the server and (important) wait for the sync_all offline timer to complete and also wait for the new order to be sent to server.
4. Create a new order. You will see this order's UID is the same as the other order.

Investigating the issue more, we found that the likely cause of this was in this block (pos_multi_session.js - send)
`
                   if (res.order_ID !== 0) {
                        self.pos.pos_session.sequence_number = res.order_ID;
                    }
`

when the action is of "sync_all" type. When the sync all arrives before the new orders are sent to the server, the sequence number is replaced to that of the order_ID on the server, but that changes when the orders created while offline are sent, so it's actually setting sequence_number to an outdated value.

We solved this by adding this on the do_ms_update function:
```
if(order_ID > self.pos.pos_session.order_ID) {
    self.pos.pos_session.order_ID = order_ID;
    self.pos.pos_session.sequence_number = order_ID;
 }
```
which makes sure that the number saved is always the latest, since this gets called on the response of the order being sent to server.

This solved the specific issue described and we thought we'd fixed it, but then some orders were still being reported as being assigned the same UID. This means that UIDs are being set equally some other way as well.

So I have a couple questions on how this whole thing works...
1. What is the purpose of keeping an order_ID in the point of sale? What's the difference between it and the normal sequence_number?
2. On ms_do_update, why is the session's order_ID set to the incoming order's sequence number? This makes the global order_ID equal to whatever the other pos terminal has edited, which could be the latest order or it could be an order made a long time ago, which to me doesn't make sense.
3. On do_ms_update, when there's a difference between the order's sequence number and the one returned from the server, why is the session's order_ID set to this new value? (same as above in point 2, but in a different place). Again, this sets the variable to a possibly outdated state.

I wanted to include my original solution to the problem in addition to just asking because that was still an issue that was fixed, but since this may be caused by something bigger I didn't want to PR just yet, since you guys know more about the module than I do.

Note that we are using odoo v9.

Look forward to hear your input. Thanks.

**Comment by yelizariev** [comment]
@pedroslopez we are working on 10.0 version and then will we backport updates to 9.0
Let's return to your feedback after that

**Comment by farazbdm** [comment]
Was this fixed ? If yes, Can you please mention where.
@yelizariev

**Comment by yelizariev** [comment]
We made improvements in 10.0, so you can try there. We don't plan to backport it to 9 version

**Comment by gustavovalverde** [comment]
Might this be our scenario @yelizariev ?

**Comment by yelizariev** [comment]
@gustavovalverde not really. In that scenario we got "reverision_error" with state="deleted". UIDs were different. It's hard to analyze this issue as it's reported about old version.

@pedroslopez I'd prefer to close this. It would be helpful if you try your scenario in the latest version of 10+ branch.
