### ISSUE TITLE
[10.0-pos_disable_payment]: Crashing the POS after Odoo update

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#388]
After Odoo update: https://github.com/odoo/odoo/commit/e14ab697727d87773dbefba11453b9edca79fc68

Now pos_disable_payment is crashing the POS (payment button won't show and products won't load).

**Comment by ilmir-k** [comment]
Hi @gustavovalverde 

Thank you for reporting this.
We've reproduced it and working on this issue currently. We will let you know once it is done.

**Comment by ilmir-k** [comment]
Hi @gustavovalverde

Glad to inform you that we fixed the issue. Please take the latest updates of pos_disable_payment and check it.

**Comment by gustavovalverde** [comment]
Tested and working, thanks @ilmir-k
