### ISSUE TITLE
[10.0-POS Advanced Order Notes ] DO NOT SYNC across diferent POS

### ISSUE THREAD

**Issue by alaherma** [itpp-labs/pos-addons#390]
I have installed these modules:
POS Advanced Order Notes
Sync POS orders across multiple sessions
Sync restaurant orders

The notes does sync when i uninstalled POS Advanced Order Notes
but i would expect  Advanced Notes would be sincronized too.

**Comment by GabbasovDinar** [comment]
@alaherma Hello, I added new functional for sync across POSes, you can check my PR #358
