### ISSUE TITLE
POS  Odoo Client Error : Uncaught type Error

### ISSUE THREAD

**Issue by ujaco** [itpp-labs/pos-addons#4]
Hi , 
When I install this addon and open the POS I get this error. When I try to close the session, I get this error repeatedly and I cant close session. 

It would be great if you can help out with this :) 
Thanks
![pos_product_available error](https://cloud.githubusercontent.com/assets/4730495/6748451/94995e76-cf0b-11e4-8fc0-061cf99097fd.png)

**Comment by yelizariev** [comment]
Hi,
could you tell name of an addon you installed.

Also, to get more information activate debug mode. Just open this url:
http://localhost:8069/pos/web/?debug

**Comment by ujaco** [comment]
The addon is pos_product_available. I tried the debug mode. It did not give me any additional information.
Thanks for the quick response!

**Comment by yelizariev** [comment]
When you in debug mode error message look a little bit different. Try again

**Comment by yelizariev** [comment]
Ok, I find posible reason of the issue. Could you update the module and try again https://github.com/yelizariev/pos-addons/commit/bcd7ea707993f82348317709b4525b67c1d0038b

**Comment by ujaco** [comment]
Works perfectly! Thanks !

**Comment by yelizariev** [comment]
Welcome!
