### ISSUE TITLE
[pos_order_cancel] question for refund

### ISSUE THREAD

**Issue by gaelTorrecillas** [itpp-labs/pos-addons#403]
Hello,

I have one "problem" with the refund.

I select one product

![image](https://user-images.githubusercontent.com/16572874/30748972-3f03e330-9fb2-11e7-9984-033456d91921.png)

I click on "+/-" to refund and I click on 5 (so I refund 5 article test) and validate this order

![image](https://user-images.githubusercontent.com/16572874/30749083-9376f074-9fb2-11e7-885e-af3194a05c4a.png)

my problem it's on backend, I have 6 quantity of my product cancelled but I refunded 5 products.

![capture du 2017-09-22 16-27-12](https://user-images.githubusercontent.com/16572874/30750089-c5ef8fae-9fb5-11e7-9716-4f76db48d839.png)

What is the reason of this "problem"? 
In my opinion, only the negative quantity, the quantity of order.line.cancellated should be the same.

**Comment by yelizariev** [comment]
@gaelTorrecillas, 6 is computed as ``max_value - new_value = 1 - (-5)=6``

I think we can register cancelling qty=1 only in this example.
Additionally, we can add filter, say "No negative refunds" in ``Reports >> Cancelations`` menu to don't have qty=1 for this product, because it's not real cancelation. 

I don't agree, that we we need to register cancelation qty=5 in this example. Usual refund via negative qty can be managed via built-in menu, while purpose of the module is registering suspicious changes

**Comment by yelizariev** [comment]
cc @GabbasovDinar

**Comment by ilmir-k** [comment]
@gaelTorrecillas 

As said @yelizariev, I think in this case the right way is to register qty=1 as cancellation quantity. 
For example, the following could be as real case to this:
Customer orders product A => qty = 1
Let's say he refuses this product or want to change it by another one
So we can cancel 1 product maximum, but not 5

**Comment by gaelTorrecillas** [comment]
@yelizariev , @ilmir-k yes, I agree with you, I suppose the final user will refund 1 product, I choose 5 to show this 'problem' because if I calcelled 1 product, we have qty = 2 in the calcelled line and It's possible that this quantity is the double.

**Comment by ilmir-k** [comment]
Hi @gaelTorrecillas 

Please check the latest updates of pos_order_cancel module. It fixes this issue

**Comment by gaelTorrecillas** [comment]
hi @ilmir-k , @GabbasovDinar ,

I don't find your branch to test this fix.

**Comment by ilmir-k** [comment]
@gaelTorrecillas 
We fixed it within the PR https://github.com/it-projects-llc/pos-addons/pull/397 which was merged into branch 10.0

**Comment by gaelTorrecillas** [comment]
@ilmir-k ; @GabbasovDinar 

thank for your work,

I tested and I have the good quantity refund thank you
