### ISSUE TITLE
[pos_keyboard]: Won't work on cashier PIN input

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#411]
Maybe this wasn't an initial "wanted" behavior, but it's definitely useful, as it's very unsafe to input a PIN with the mouse.

**Comment by gustavovalverde** [comment]
Hi @yelizariev, this one should be simple. Who can help us here?

**Comment by yelizariev** [comment]
pos_keyboard is not really popular and we almost don't maintain it. Consider sponsoring this update.
