### ISSUE TITLE
[10.0-pos_order_note]: Send additional notes to kitchen

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#413]
This would be a "nice to have" feature:

Maybe we forgot something when we sent to the kitchen, or forgot to add a note. Right now I see no way to add additional notes to an already sent orderline

**Comment by gustavovalverde** [comment]
The first one was just a bug on my side

**Comment by yelizariev** [comment]
After making changes in kitchens products you can click "Order" again and it has to print updates. I suppose it's a bug if it doesn't work this way, because it worked

**Comment by gustavovalverde** [comment]
Tested, and working. I'll open a different but related issue.
