### ISSUE TITLE
Pos_disable_payment : Remove Orde line is not applied

### ISSUE THREAD

**Issue by mslokhat** [itpp-labs/pos-addons#42]
Hi,

if the restriction : Allow remove orde line is unset , the Backspace button is still there :

![image](https://cloud.githubusercontent.com/assets/8535048/11820354/74d52b78-a37d-11e5-83ba-eb1dbf13b0a6.png)

**Comment by yelizariev** [comment]
thanks, we'll check it soon

**Comment by mslokhat** [comment]
Hi, 
can you review and close this issue?

**Comment by yelizariev** [comment]
You need this button to correct numbers, we cannot remove it. But checkbox " Allow remove orde line" should works -- it just ignores Backspace button clicking
