### ISSUE TITLE
[10.0-pos_debt_notebook]: Invading Receipt customization on pos.xml 

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#426]
In the pos.xml we have a nice, but harmful feature, which adds the customer to the ticket. But it breaks already customized tickets, and also uses a no translatable word. 

See:
https://github.com/it-projects-llc/pos-addons/blob/bd1ef7667b4bef2d330126acf1b1a74e86be6b85/pos_debt_notebook/static/src/xml/pos.xml#L150

**Comment by yelizariev** [comment]
I'll update it in 11.0, but not sure how to safely remove it in 10.0
