### ISSUE TITLE
[10.0-pos_order_note] Predefined notes not being sent to Kitchen

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#428]
Just the notes that are written are being sent to the kitchen, the predefined notes are just shown in the orderlines screen, but not sent.

Also, after an orderline has been sent to the kitchen, and I write a note in the textbox, the "Order" button highlights in green, but this does not happen with the predefined notes.

**Nice to have:** If a predefined note has not been sent, show it in green. If it has been sent, show it in black (default color being used now).

cc: @yelizariev

**Comment by dhecar** [comment]
I confirm this issue, also, the note doesn't propagate to other multisession

**Comment by GabbasovDinar** [comment]
hello @gustavovalverde , @dhecar you can chek the PR https://github.com/it-projects-llc/pos-addons/pull/358

**Comment by gustavovalverde** [comment]
Just an FYI, as this is not working yet on my side.

**Comment by gustavovalverde** [comment]
@GabbasovDinar, just a reminder on this one. Still not working as reported by users.

**Nice to have:** If a predefined note has not been sent, show it in green. If it has been sent, show it in black (default color being used now).
