### ISSUE TITLE
Printing method not work

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#432]
Hello, I found a new issue, the printing method does not work after upgrade to the latest pos-addons. plz, help.
also when I change printing method it lost all floor ids needs to re-config again.

**Comment by GabbasovDinar** [comment]
Hello @W360S, you can check the PR https://github.com/it-projects-llc/pos-addons/pull/416

**Comment by 360org** [comment]
Hi @GabbasovDinar i have check but not understand, what do i do now?

**Comment by ilmir-k** [comment]
Hi @W360S 

We are working on this issue and let you know once we fix it. Thanks

**Comment by GabbasovDinar** [comment]
@W360S hello, I Fixed this issue

**Comment by 360org** [comment]
Thanks, @GabbasovDinar @GabbasovDinar  really appreciated im going to update tomorrow :)
