### ISSUE TITLE
[10.0] pos_debt_notebook doesn't work well with credit notes

### ISSUE THREAD

**Issue by edser-pcg** [itpp-labs/pos-addons#433]
When an order is paid with a Debt diary and later user needs to revert that transaction through a Credit Note it will pop an error stating that the customer doesn't have enought credit.

ie.
1. Customer pays order with "debt method" $1,000.00 with a max allowed credit set to $1,500.00
2. User tries to apply a Credit Note to that same order.
3. POS states that the customer doesn't have enough credit.

Seems like if it where calculating 1,000 + 1,000 = 2,000 > 1,500 instead of 1,000 - 1,000 = 0 < 1,500

CC: @gustavovalverde SE

**Comment by yelizariev** [comment]
What is Credit Note?
