### ISSUE TITLE
Pos_disable_payment : Change Cashier does not apply on allow_delete_order_line rule

### ISSUE THREAD

**Issue by mslokhat** [itpp-labs/pos-addons#45]
Hi,

The scenario :
1. login as a user with restriction : allow_delete_order_line = unchecked
2. the user cannot decrease or remove the line (qty == 0 ) ==> GOOD
3. in the pos itself , we change the Cashier and select a cashier who has : allow_delete_order_line = checked
4. remove line still is locked, quantity cannot be changed.

**Comment by yelizariev** [comment]
Try newest version. We have fixed general issue with changing cashier

**Comment by mslokhat** [comment]
Hi,

still found some issues , and corrected them :

replace the code below : 

screens.NumpadWidget.include({
        clickDeleteLastChar: function(){
            var user = this.pos.cashier || this.pos.user;
            //if (!user.allow_delete_order_line && this.state.get('buffer') === "" && this.state.get('mode') === 'quantity'){
            if (!user.allow_delete_order_line  && this.state.get('mode') === 'quantity'){  
                return;
            }
            else
                return this._super();
        },
        clickAppendNewChar:function(event) {
            var user = this.pos.cashier || this.pos.user;
            if (!user.allow_delete_order_line  && this.state.get('mode') === 'quantity'){  
                return;
            }
            else
                return this._super(event);
        },
        clickSwitchSign: function() {
            var user = this.pos.cashier || this.pos.user;
            if (!user.allow_delete_order_line){  
                return;
            }
            else
                return this._super();
        }
    })

---

Purpose :

Cashier with restrictions can only add products , if he want to deduct or remove line , he will have to call his manager

**Comment by yelizariev** [comment]
So, it means that if he wants to add 2 products and clicks 2 twices, then he will not able able to fix it?
Need your experienced advice.

**Comment by mslokhat** [comment]
Hi,

Yes. exactly. the cashier should at any time to be able to reduce items. it only increase. 

if he makes an error, he needs permission from his manager.

**Comment by yelizariev** [comment]
ok, I'll do it

**Comment by yelizariev** [comment]
done #51
