### ISSUE TITLE
[10.0-pos_debt_notebook]: Generate a debt without a payment

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#480]
I've always wonder if it's possible to make pos_debt_notebook work like a common sale on credit on the backend --> You make an invoice without payments, and this goes to the Accounts Receivable (AR); then when the payment is received the AR account is deducted (the debt is deducted).

This is trying to keep the normal "Odoo Flow" of Accounts Receivable. Is this somehow possible or in roadmap?

**Comment by gustavovalverde** [comment]
My expected result is an invoice in the "open" state, without a payment attached.

Otherwise my Accounts Payable won't show the reality of the whole company, and the Accounting Person has to check the Accounts Payable report and also the PoS debts report and sum both.

**Comment by yelizariev** [comment]
It may be some extension which creates "Manual Update" when debt is created (e.g. invoice is open) and debt is payid (invoice is paid).
But probably more direct solution is better for such cases

**Comment by gustavovalverde** [comment]
Hi @yelizariev, I could fund this as I'm actually needing this functionality, is practically not attaching the Journal Payment with each credit sell on the PoS, thus leaving the Invoice Open.

**Comment by ilmir-k** [comment]
Hi @gustavovalverde

We are going to analyze it. 
Please could you describe in more detail this issue to understand it more clearly? 
Also examples could help us. Thanks

**Comment by gustavovalverde** [comment]
I'd like to make a sales on the POS, with the same workflow as you guys have. The thing is that I'm on anglo-saxon (continental) accounting, where each sale is invoiced. Every sale on the POS is invoiced in the backend in realtime.

If I pay with debt, this invoice should not be paid...it must stay open. Because the customer will return later and pay the invoice, but right now is not possible as the invoice shows as already paid by the debt (this also makes it harder for follow-ups for Accounts Receivable).

Mainly, the debt system is "paying" the invoice, but it shouldn't if its a debt. This way I can close the invoice later when I receive the payment from the customer.

What I'd like to implement is that if the debt method is used, that it does not create an account.payment, it just affects the client debt. But also, if I receive a payment from that client on a _debt-invoice_, that his debt is reduced.

Is that use case understandable? As right now the credit/debt system assumes that the partner already has "paid" (when using invoices). And this is OK when using credits (pre-paid) but not with debts (account receivable).

**Comment by gustavovalverde** [comment]
@ilmir-k let me know if you need further clarification and the starting funding balance for it.

**Comment by ilmir-k** [comment]
Hi @gustavovalverde 

Sorry for the delay with response. We had long 10-days new holidays in Russia.
Thanks for the clarification. It is more clear now. We'll analyze it and give our feedback asap.

**Comment by ilmir-k** [comment]
@gustavovalverde
For example, we have a Product = 90 usd
If we pay this product via POS using debt journal and then we close&post entries we will have the following account payment record:

![account_payment](https://user-images.githubusercontent.com/14342645/35055622-67f7bdfe-fbd1-11e7-8dbf-4ac5bf00587b.png)


and journal items: 

![entries](https://user-images.githubusercontent.com/14342645/35055471-1711a3fa-fbd1-11e7-96b7-513c73ce475c.png)

As we understand in your case we should not create a payment.account record.
And what about journal items? should we not create the items generated by debt journal (colored by red rectangular)?

**Comment by gustavovalverde** [comment]
@ilmir-k 
That's correct. We don't want a payment.account record neither it journal items.

If you, for example, create an invoice in Odoo, without a payment, it just create the journal items of the invoice. That would be the needed behavior but for the POS.

In this case, the Debt Journal will only be a Payment Button in the POS that leaves the pos.order open, without a payment attached to it.

The only "interesting" thing that we should be aware is that when closing the POS, in the Session Closing, it should somehow show how much was "sold with "debts".

**Comment by gustavovalverde** [comment]
Thinking it twice: 
> The only "interesting" thing that we should be aware is that when closing the POS, in the Session Closing, it should somehow show how much was "sold with "debts".

This part might be too hard if you don't have an `account.payment` record. This record is harmless as long as it does not affect my accounting. It could even help on Session Closing to know how much was sold with debt. 

I'll leave this part to your best initial analysis from a programming side, and I could do as much QA as possible to validate the behavior.

**Comment by ilmir-k** [comment]
@gustavovalverde

We made some analysis and the possible solution might be as follows:
If we pay by Debt Journal, we could make 100% discount for such payments. So it will not generate accounting items for debt journal.
I.e. if we pay Product = 90 usd using Debt journal, we will have the following pos receipt:

![pos_receipt](https://user-images.githubusercontent.com/14342645/35614842-37acb836-0692-11e8-91b0-8d045c1e4219.png)

After closing POS session, we would have the journal entries (items) like:

![journal_entries](https://user-images.githubusercontent.com/14342645/35614909-6b070e3e-0692-11e8-9d6d-0751a56d56dd.png)

It doesn't contain debt journal information, there are Pos Sale journal items only, which have value 0 due to 100% discount 
Also we will not have `account.payment` record for Debt.

As usual the Debt information you can see at Debts/Credits report:

![report](https://user-images.githubusercontent.com/14342645/35616012-b7d05916-0695-11e8-8206-1b0d662f6014.png)


Then if customer is going to pay his debt, you could create usual invoice for that operation. 

Please share your thoughts.

**Comment by ilmir-k** [comment]
@gustavovalverde
We have not received response regarding this for a long time. Is that actual for you?
