### ISSUE TITLE
POS Keyboard Qty conflict

### ISSUE THREAD

**Issue by cholitoecuatoriano** [itpp-labs/pos-addons#49]
The quick scan a bar code bar number is included in the amount.

**Comment by yelizariev** [comment]
Can you say what module and odoo version do you use

**Comment by cholitoecuatoriano** [comment]
II'm using Odoo 8 modules: Point of sale, pos_keyboard, pos_debt_notebook.
I'm looking for a solution to PC without touchscreen.
Thank you for your help. Good job

**Comment by yelizariev** [comment]
Those modules are not related to barcode scanning
