### ISSUE TITLE
pos_keyboard: Suggestion when using barcode scanner

### ISSUE THREAD

**Issue by sibuxiang** [itpp-labs/pos-addons#50]
Hi,

The module is great and it performs as proposed, but I'm having problems using this module with a barcode scanner.
If I scan a product the program recognize the barcode and show the item and if I scan another item the quantity becomes the barcode scanned and then appears the next item.
I suggest that for better use of the keyboard shortcuts maybe add crtl or alt key to execute.

Great job!

**Comment by yelizariev** [comment]
Thanks for report.

It's possible to fix it without adding ctrl or alt keys. Wait for updates.

**Comment by mobmohan** [comment]
Hi
I am facing the same problem. Its actually working fine with touch.but if u use scanning creating issues. can u please update me when its fixed.

**Comment by yelizariev** [comment]
Updates are coming in #53 and #62 .
