### ISSUE TITLE
Try new collaboration friendly repo structure

### ISSUE THREAD

**Issue by blaggacao** [itpp-labs/pos-addons#505]
I think, I don't need to elaborate much on the inconveniences of coupling and the benefits of uncoupling in general.

I'd really like to design a workflow in my team, so that close collaboration on the different it-projects modules will become as easy and convenient as possible. So far I got:
```bash
git remote add my-russian-friends-pos-sync-module https://github.com/it-projects-llc/pos-sync-module
git subtree add —-prefix=pos_sync_module my-russion-friends-pos-sync-module master

```
Do some commits and feed them back (my inherent urge for reciprocity is calling)...
```bash
git subtree split --prefix=pos_sync_module --annotate='(split) ' --rejoin --branch pos-sync-module-split
git push https://github.com/FORKED/pos-sync-module pos-sync-module-split:master  # Do a PR, then
```
... and pull from upstream
```bash
git subtree pull --prefix=pos_sync_module
```

However, for this to work that easily there is one precondition: 

##### one module = one repo

Advantage: The easier collaboration becomes over time, the better grows the codebase...
And sometimes we, at XOE, can be a powerhouse, as well. :wink: 

PS: Don't copy the strategic errors of the OCA :wink: Repo and folders are two of a different kind...

**Comment by blaggacao** [comment]
This is how I work around, but I have no idea how to feed my local changes back through this pipeline... So reciprocity is technically (subjectively) blocked in this case, which really annoys me.


(ideas for nomenclature)
```
    git remote add -f it-project-llc/mail-addons ../it-projects-llc/mail-addons
    git remote add -f it-project-llc/misc-addons ../it-projects-llc/misc-addons
    git remote add -f it-project-llc/pos-addons  ../it-projects-llc/pos-addons
    
    git checkout -b staging/it-project-llc/mail-addons/11.0 it-project-llc/mail-addons/11.0
    
    git checkout -b staging/it-project-llc/misc-addons/11.0 it-project-llc/misc-addons/11.0
    
    git checkout -b staging/it-project-llc/pos-addons/11.0  it-project-llc/pos-addons/11.0
    git subtree split -P pos_disable_payment          -b split/it-project-llc/pos-addons/pos_disable_payment/11.0
    git subtree split -P pos_longpolling              -b split/it-project-llc/pos-addons/pos_longpolling/11.0
    git subtree split -P pos_multi_session            -b split/it-project-llc/pos-addons/pos_multi_session/11.0
    git subtree split -P pos_multi_session_restaurant -b split/it-project-llc/pos-addons/pos_multi_session_restaurant/11.0
    
    git checkout master
    git subtree add -P it-projects-llc/pos_disable_payment          split/it-project-llc/pos-addons/pos_disable_payment/11.0
    git subtree add -P it-projects-llc/pos_longpolling              split/it-project-llc/pos-addons/pos_longpolling/11.0
    git subtree add -P it-projects-llc/pos_multi_session            split/it-project-llc/pos-addons/pos_multi_session/11.0
    git subtree add -P it-projects-llc/pos_multi_session_restaurant split/it-project-llc/pos-addons/pos_multi_session_restaurant/11.0
```

**Comment by blaggacao** [comment]
This hits the dog, really! https://github.com/ingydotnet/git-subrepo

**Comment by blaggacao** [comment]
Reduced to the following:
in your `pos-addons`:
```
git subrepo init pos_disable_payment
git subrepo init pos_longpolling
git subrepo init pos_multi_session
git subrepo init pos_multi_session_restaurant
```
and in my container project:
```
git subrepo clone ../it-projects-llc/pos-addons/ it-projects-llc/pos_disable_payment          -b subrepo/pos_disable_payment
git subrepo clone ../it-projects-llc/pos-addons/ it-projects-llc/pos_longpolling              -b subrepo/pos_longpolling
git subrepo clone ../it-projects-llc/pos-addons/ it-projects-llc/pos_multi_session            -b subrepo/pos_multi_session
git subrepo clone ../it-projects-llc/pos-addons/ it-projects-llc/pos_multi_session_restaurant -b subrepo/pos_multi_session_restaurant
```

Insanely simple, isn't it?

Still no idea how to feed back, unless you had split up into subrepos, then my local improvmeents would go upstream without hassle like this: `git subrepo push pos_longpolling` - perfectly formatted and all, ready for PR.

And you would probably update your subrepo-ed "topic-repo" (`pos-addons`) with `git subrepo pull --all` every now and then...

**Comment by blaggacao** [comment]
@yelizariev Plain OCA would never go forward with this efficiency boost, but you probably would? :wink:

**Comment by yelizariev** [comment]
So, as I understand, you want a way to have a repo with only specific modules from other repositories. As you described, you can use git subtree or similar tools for it. And the question is how to make updates on that repository in a way that allows to make a PR to original repository (e.g. pos-addons) easily.

Is it correct? Did I miss something?

I took a look on git subtree command and seems that it may work with entire project only, i.e. for example you cannot attach pos_longpolling from https://github.com/it-projects-llc/pos-addons/ *directly*. Only with workarounds as you described.

Which options I see.

Option 1.

* Use one of your way to attach only modules you need from pos-addons
* Now, update one fo the modules. Make commits
* Then someway attach commits to a normal fork of pos-addons (probably via ``git cherry-pick``)?

Options 2.

* Make pos-addons set of subtrees
* One can use ``git subree`` directly  from coresponding repository (e.g. it-projects-llc/pos-addons-pos_longpolling)
* PR can be done to module repository or (hopefully it will work) to pos-addons

Options 3.
Find some tool or make a script, that allows to attach modules from pos-addons and send updates back. I.e. without any changes in current structure

P.S. A way I prefer is to consider subtree in a project as a readonly and make a PR via normal workflow. Alternativly, I can attach repositories with all modules to addons-path. Later allows to makes commits from the same folder that are used in deployment. But, I'm ready to change to mind if we find an easy way to attach modules and send commits from them to original repository

**Comment by yelizariev** [comment]
https://Odoo.sh use following approach:

They suggest to make submodule of entire pos-addons to the repo. Then they system detects folders with addons and add it to addons path.

Again, it means that you attach all modules, including ones, which you don't need, but is it really a problem?

**Comment by blaggacao** [comment]
I've used submodules for some time now, as odoo.sh suggests, and I'm really not satisfied...
What most bothers me is that I cannot get easily clean and transparent changelogs...

I'll use git subrepo from now on, its really simple and very battle tested...

I was thinking of doing a sample fork repo (I could start with your pos-addons, if you don't mind), by some git api script in order to show what would be the best way to collaborate in the odoo ecosystem...
I think option 2 is what aI have in mind:

For compatibility:
```
pos-addons (github repo)
- module 1 (.gitrepo)
- module 2 (.gitrepo)
```
For collaboration:
```
module 1 (github repo)
module 2 (github repo)
```

The latter repos would be the repos to do simple isolated pullrequests to...

With the gitrepo/subtree thing you even don't have to suffer inconvenience when you want to make a commit which touches different gitrepos, they transparently get spliced and pushed once you want to push upstream.

**Comment by blaggacao** [comment]
closed as just a means of sharing ideas... No real issue.
