### ISSUE TITLE
pos_product_category_discount: will not work well enough with pos_cache

### ISSUE THREAD

**Issue by dek-odoo** [itpp-labs/pos-addons#507]
The module `pos_cache` is used for the purpose of improving load time in case of thousands of products.
The module `pos_product_category_discount` [loads](https://github.com/it-projects-llc/pos-addons/blob/11.0/pos_product_category_discount/static/src/js/discount_program.js#L258) `product.template` (apart from the product cache) .

1. Loading `product.template` increases the load time a lot.

2. When pos_cache is installed, `product.product` is loaded last from load_server_data and loading product.template depends on products. So loading `product.template` will fail as there will be nothing in pos.db.product_by_id

To fix this we can add the field `discount_allowed` in load_server_data, something like the following:

        load_server_data: function () {
            var self = this;
            var product_index = _.findIndex(this.models, function (model) {
                return model.model === "product.product";
            });
            var product_model = this.models[product_index];
            var product_fields = product_model.fields;
            product_fields.push('discount_allowed');
            product_fields.push('product_variant_ids');
            product_fields.push('write_date');
            return posmodel_super.load_server_data.call(this, arguments);
        },

Thank you

**Comment by GabbasovDinar** [comment]
Hello, @dek-odoo 

I fixed the issue. You can check it https://github.com/it-projects-llc/pos-addons/pull/493

**Comment by dek-odoo** [comment]
:+1: @GabbasovDinar
