### ISSUE TITLE
[hw_printer_network] Keeps on trying to connect, even though found

### ISSUE THREAD

**Issue by thomaspaulb** [itpp-labs/pos-addons#513]
Hi there, I have noticed that the `hw_printer_network` module keeps on trying to connect to the 9100 port of each network printer every 2 seconds or so, even though it has found all (1) of them. [This code](https://github.com/it-projects-llc/pos-addons/blob/10.0/hw_printer_network/controllers/hw_printer_network_controller.py#L33) is executing. I would expect a delay of at least 5 seconds because of the `sleep`, but I think that two main loops are running in parallel.

Other than that - why are connection reopened all the time and not cached until they time out? Is there a design reason for that or was that just not implemented yet?

**Comment by GabbasovDinar** [comment]
hello, @thomaspaulb 
Yes, it's not implemented yet. What improvements could you offer?
regards

**Comment by thomaspaulb** [comment]
Well, am currently facing a blocking issue with this, because when the
module runs a while, port 9100 of the printer gets really overloaded with
all the requests and starts lagging.

I have to come up with a solution; my thinking would be to:
- change the online check to a regular ping
- do this asynchroneously and cache the results
- the http status check would just return the cached values, or place the
check in the queue when it is an ip address not currently known
- coexist better with the usb driver, by getting rid of "without_usb" and
other refactoring. Here i am not sure if its best to keep the current
solution of extending the escpos driver or registering as a separate
network_escpos driver.

Any suggestions before i start on it?



Op 1 dec. 2017 08:39 schreef "Dinar" <notifications@github.com>:

**Comment by GabbasovDinar** [comment]
>  - coexist better with the usb driver, by getting rid of "without_usb" and
> other refactoring. 

@thomaspaulb I have made this offer to get rid of the print delay in the 'network' printer. If we do not point out that USB printer isn't used then self.queue will always have checking of USB printer connection. Because of it, the task to immediate print will not be done

**Comment by thomaspaulb** [comment]
Well, that is true. But I think if we remove [this](https://github.com/it-projects-llc/pos-addons/blob/10.0/hw_printer_network/controllers/hw_printer_network_controller.py#L130), there should be now two drivers with separate queues running - one for the USB, and one for network. If we then remove lines such as [this one](https://github.com/it-projects-llc/pos-addons/blob/10.0/hw_printer_network/controllers/hw_printer_network_controller.py#L78) so that the second driver handles network printers only, both USB and network printers should be handled well, and don't need to wait on each other since they have separate queues and threads?

**Comment by GabbasovDinar** [comment]
@thomaspaulb Yes, I agree with you.
@yelizariev What do you think?

**Comment by yelizariev** [comment]
@GabbasovDinar I trust you

**Comment by thomaspaulb** [comment]
Thanks guys - now working on it, will submit a PR this week.

**Comment by robinshakty** [comment]
Hi Thomas,
I downloaded your module pos_printer_network, and the pos freezes after the step 'Connecting to posbox), if I activate reeceipt printer for posbox.
Do you have an explanation ?
Thanks 
sebastien

**Comment by thomaspaulb** [comment]
Hi Robin, it is not my module but it was made by @GabbasovDinar. I just
made some changes in this PR, but they are not fully tested yet. Are you
using the main branch or the branch as changed by me?

**Comment by robinshakty** [comment]
I wanted to test your changes from your PR because I had the problems you found with the other module.
and the pos ddoes not start with the version of your module pos_printer_network.
Do you think I can use your hw_printer_network module with the pos_printer _network of gabbasovdinar ?

**Comment by GabbasovDinar** [comment]
@robinshakty Unfortunately I haven't tested the work of @thomaspaulb so I can't answer Your question. But I will check it soon...

regards

**Comment by thomaspaulb** [comment]
@robinshakty Could you post a screenshot or literal copy of the error in the browser console that accompanies the freeze?

**Comment by thomaspaulb** [comment]
@robinshakty I have rebased this PR onto the latest 10.0 branch, maybe that could help. 

As to your question if you can use this `hw_printer_network` module with the old `pos_printer _network` module, it should be possible, I just removed some Javascript that is not needed anymore, but both versions should work. But if you post the error, we can find out if there is still any bug with that.

**Comment by yelizariev** [comment]
Done in #563 by @thomaspaulb
