### ISSUE TITLE
[10.0] Restaurant multi session error with full browser freeze (Chrome)

### ISSUE THREAD

**Issue by thomaspaulb** [itpp-labs/pos-addons#520]
When opening a certain order that has a pending change that still needs to be sent to the kitchen, and pressing "Order", we are getting a red screen saying:

"There is a conflict during synchronization, try your action again"

And the browser becomes unresponsive.

**Comment by GabbasovDinar** [comment]
@thomaspaulb How do you get the error? Write step by step, please 

Thanks
@KolushovAlexandr

**Comment by yelizariev** [comment]
Also, please test againt latest version. We pushed one big update recently https://github.com/it-projects-llc/pos-addons/commit/d7e2db69fa2dc80d47f3ee7fc69dd33bf60858f0#diff-69280bd2879a0334b3dadb77af444094
