### ISSUE TITLE
Unnecessary text overlay on POS after installing POS Order Notes

### ISSUE THREAD

**Issue by novatorapps** [itpp-labs/pos-addons#527]
Hi. When I install POS order notes, I see unnecessary text overlayed on POS after installing POS order Notes. 

Screenshot: https://www.dropbox.com/s/m8322hxoxhuiwlw/Screenshot%202017-12-09%2019.22.39.png?dl=0

Thanks

**Comment by yelizariev** [comment]
@GabbasovDinar it should be that problem with tour. What is the solution? Could you fix it?

**Comment by GabbasovDinar** [comment]
@yelizariev,DONE

**Comment by novatorapps** [comment]
Thanks guys! I appreciate the great work you are doing. I am not technical person and relatively new here. I have just got on board a technical team member and we will hopefully be contributing to your modules soon. Thanks
