### ISSUE TITLE
*Feature Request* Integrate pos_pin in pos_order_cancel module

### ISSUE THREAD

**Issue by novatorapps** [itpp-labs/pos-addons#538]
Every mainstream and reliable POS system for restaurants/retailers has strict controls for certain actions like applying discount or canceling an item after it has been sent to kitchen. Only a designated user e.g. a manager can perform these actions after punching his pin on POS screen. 

You already have a module pos_pin which is integrated with pos_product_available_negative. Can we have same integration with pos_order_cancel module. When a user clicks 'Cancel' or 'Delete' button, a popup will come up with users who have a 'POS Manager' role. Upon selecting a user from popup, the manager will enter his pin, get verified and then cancel an item. The Refund/Cancellation report at back will have the name of user who authorized the cancellation. 

I will be happy to sponsor this.

**Comment by yelizariev** [comment]
Hi,
we like to use services like https://bountysource.com, https://gitcoin.co/ for sponsoring issues. Do you use any of them?

**Comment by novatorapps** [comment]
Yelizariev. Thanks for getting back. I have just created an account on BountySource. I will create bounty. Please let me know what is the appropriate bounty value. 

The module should have option to specify when the security popup should be triggered- any time during the order or after the order is sent to Kitchen. 

Thanks

**Comment by GabbasovDinar** [comment]
@ilmir-k Can I start the work?

**Comment by ilmir-k** [comment]
Hello @passion342

We would be glad to help you.

We estimated the work required for this task and it will cost 780 usd. 
Please let us know if it is ok for you. Thanks

cc @GabbasovDinar

**Comment by novatorapps** [comment]
Thanks @ilmir-k 

I would love to $780 but unfortunately I can't pay that much at the moment. I can send $100 now. If someone else needs this functionality, they can contribute. Else, you can work on this when you feel time is right. Thanks for understanding

**Comment by ilmir-k** [comment]
@passion342 It's ok. We can do as you offer. Thanks

**Comment by novatorapps** [comment]
Thanks @ilmir-k. I will send money. No obligations. You can work whenever you can. I was trying Bounty Source but unfortunately Paypal doesn't work in Pakistan. I will have to explore Bitcoin or Ethereum. Any other way to transfer money? Thanks

**Comment by ilmir-k** [comment]
@passion342 
We also use Payoneer service https://www.payoneer.com for payments. Did you use it? Does it work in your country?

**Comment by novatorapps** [comment]
Thanks. Yes- I use Payoneer.

**Comment by ilmir-k** [comment]
Hi @passion342
Happy New Year to you!
Sorry for the delay. We had 10-days new year holidays until today.
Good, we could send invoice via payoneer. Please let us know what email do you use for your payoneer account to be able to send invoice ?
Thanks

**Comment by novatorapps** [comment]
Hi @ilmir-k. 

Thanks. Hope you had great holidays. Please do. I have sent you an email. Please check it.

**Comment by gustavovalverde** [comment]
This can be closed @yelizariev
