### ISSUE TITLE
POS Multi Session: POS picking up the last user who used POS and not the current user who started session

### ISSUE THREAD

**Issue by novatorapps** [itpp-labs/pos-addons#548]
I came across an issue on an issue where POS picks up the last user who used POS and not the current user who started session. This happens on both the same and another point of sale. I created a completely fresh DB and reproduced the issue. Here's the video illustrating the issue:

https://youtu.be/7JZ9PI-C-Uw

**Comment by ilmir-k** [comment]
@Railia check it please

**Comment by gustavovalverde** [comment]
Maybe this is a fix for that: https://github.com/odoo/odoo/commit/54d1b38844a79724a77268dc577b771b8c9f6321

**Comment by gustavovalverde** [comment]
This can be closed as it was fixed by Odoo cc: @yelizariev
