### ISSUE TITLE
Scrolling for pos_mobile (pos_mobile_restaurant) on iOS [$50 awarded]

### ISSUE THREAD

**Issue by ilmir-k** [itpp-labs/pos-addons#550]
We need someone who can resolve scrolling issue for pos_mobile (pos_mobile_restaurant) on iOS:

**_Actual behavior:_**
  
  The scroll bar is always displayed even if we don't scroll

![ios3](https://user-images.githubusercontent.com/14342645/34441266-5c35d464-ecdc-11e7-9d18-64e24b1f255e.png)

**_Expected behavior:_**
  
  The scrollbar is hidden in the interface. When sliding, the scroll bar is displayed. After the slide is finished, the scroll bar is hidden again. 

**_Technical information:_**

* It seems, that desired behavior is not possible on Android
* For iOS it can be done via ``-webkit-overflow-scrolling: touch``. But it has problem with rendering (hidden elements are not fully rendered after scrolling to them)

For usage instruction and other notes see: https://github.com/it-projects-llc/pos-addons/issues/549#issuecomment-354550123

**Comment by yelizariev** [comment]
Actually, the same behavior on Android

**Comment by yelizariev** [comment]
Ok, the situation is as following
* Desired behavior is not possible on Android 
* For iOS it can be done via -webkit-overflow-scrolling. But it has problem with rendering (hidden elements are not fully rendered after scrolling to them)

**Comment by yelizariev** [comment]
@ilmir-k can we pay out  the bounty for @GabbasovDinar ? It is fixed?

**Comment by ilmir-k** [comment]
> @ilmir-k can we pay out the bounty for @GabbasovDinar ? It is fixed?

@yelizariev yes, we can. It has been fixed.
