### ISSUE TITLE
Impossible to install pos_debt_notebook

### ISSUE THREAD

**Issue by flotho** [itpp-labs/pos-addons#56]
Hi Ivan,

We have a problem while installing the module on an already existing database.
Here is the message :

```
File "/home/pascal/DEV/Serveurs/odoo9/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "The company of a payment method is different than the one of point of sale
None" while parsing /home/pascal/DEV/lib_Odoo/v9/yelizariev/pos-addons/pos_debt_notebook/data.xml:32, near
<record id="point_of_sale.pos_config_main" model="pos.config">
            <field name="journal_ids" eval="[(4, ref('pos_debt_notebook.debt_journal'))]"/>
        </record>
```

Any ideas ?

**Comment by yelizariev** [comment]
Seems like you use multicompany mode.

I'll try to find solution for this.
For a while, delete this record tag from /home/pascal/DEV/lib_Odoo/v9/yelizariev/pos-addons/pos_debt_notebook/data.xml

then install module and then 
make a duplicate for Debt Journal and specify another company you use

**Comment by yelizariev** [comment]
@ufaks

**Comment by flotho** [comment]
Thanks @yelizariev,
I'll give it a try

**Comment by flotho** [comment]
Looks to be a good workaround

**Comment by flotho** [comment]
This one is Ok with your workaround
