### ISSUE TITLE
[9.0] pos_multi_session_restaurant Order screen changes after payment

### ISSUE THREAD

**Issue by JACG29** [itpp-labs/pos-addons#573]
Hello, when using the pos_multi_session_restaurant module I ran into an issue. 

When two or more sessions are open and one of them finish a payment, the other ones changes to the previous table they opened and the order changes to an apparently random one.

I'm using Odoo 9.0 

Thanks.

**Comment by yelizariev** [comment]
Which behavior do you expect? 
It most likely that we will work on this issue only if you provide proof of the payment for this module 
https://www.odoo.com/apps/modules/9.0/pos_multi_session_restaurant/

**Comment by JACG29** [comment]
Sorry, I through this addons were open-source, I found them in git before checking in odoo
