### ISSUE TITLE
Test script to check POS error messages

### ISSUE THREAD

**Issue by Railia** [itpp-labs/pos-addons#592]
Tests cover errors included in the file (pos_debt_notebook/static/src/js/pos.js) 
Error 1
1.	Resume POS
2.	Choose product
3.	Go to Payment
4.	Select Debt Journal
5.	Set Customer
6.	Select Debt Journal
7.	Deselect Customer
8.	Validate
9.	Get the error:  "You cannot use Debt payment. Select customer first."

Error 3
1.	Resume POS
2.	Go to Payment
3.	Validate
4	Get the error: “There must be at least one product in your order before it can be validated.”

Error 4

1.	Resume POS
2.	Choose products with sum exceed 1000 $
3.	Go to Payment
4 Set Customer (his max debt 1000$)
5 Select Debt Journal
6 Tender exactly the whole due
7 Get the error: "You cannot sell products on credit to the customer because his max debt value will be exceeded."

New scenarios  for pull request https://github.com/it-projects-llc/pos-addons/pull/597
Put cash to credit account:
1. Resume POS
2. Buy Pay debt
3. Go to Payment
4. Select customer
5. Choose Cash journal
6. Enter Tender amount 
7. Choose Credit journal
8. Validate
Result: Credit amount is increased.

Transfer money from Credit journal to Credit (Fruit&Vegetables only)
1.Resume POS
2. Buy Pay debt
3. Go to Payment
4. Select customer
5. Choose Credit journal
6. Enter Tender amount 
7. Choose Credit journal (Fruit&Vegetables only)
8. Validate

Result: Credit amount is decreased
Credit (Fruit&Vegetables only) amount is increased

Error 5 :

Transfer money from Credit (Fruit&Vegetables only) to Credit journal 

1.Resume POS
2. Buy Pay debt
3. Go to Payment
4. Select customer
5. Choose Credit journal Fruit&Vegetables only)
6. Enter Tender amount 
7. Choose Credit journal 
8. Validate
9. The error shows: Please enter the exact or lower debt amount than the cost of the order.

The same error with Cash, Credit (via discounts) journals

Error 6
1. Set PIN for Demo
2. Resume POS
3. Change Admin to Demo
4. Set Incorrect PIN
5. Get error: Incorrect Password

Black screen initial load check in POS
1. Press F12
2. Select Slow Internet
3. Resume POS
4. Check the console that the debt_hystory was loaded while the black screen is loading

**Comment by yelizariev** [comment]
@KolushovAlexandr review this please

**Comment by KolushovAlexandr** [comment]
Error 3
a customer is not necessary

Error 4
4 Set Customer (his max debt 1000$)
5 Select Debt Journal
6 Tender exactly the whole due
7 Get the error: "You cannot sell products on credit to the customer because his max debt value will be exceeded."

Error 5
If demo data is on start from the step 2 and use Credits (Fruits & Vegetables only) (USD) as a journal to pay

Transfer money from Credit (Fruit&Vegetables only) to Credit journal is equal to Error 5

**Comment by Railia** [comment]
I don't understand that: 
Error 5
If demo data is on start from the step 2 and use Credits (Fruits & Vegetables only) (USD) as a journal to pay

Transfer money from Credit (Fruit&Vegetables only) to Credit journal is equal to Error 5

**Comment by KolushovAlexandr** [comment]
How I could see, my changes are taken into account.
It seems that all is fine now
