### ISSUE TITLE
[V9]Impossible to close the debt in tg_pos

### ISSUE THREAD

**Issue by flotho** [itpp-labs/pos-addons#61]
Hi,

here is a problem while trying to close the debt of the customer :

```
TypeError: this.cashregister.journal_id is undefined
http://erp.manucentre.fr/point_of_sale/static/src/js/models.js:1429
Retraçage :
exports.Paymentline<.initialize@http://erp.manucentre.fr/point_of_sale/static/src/js/models.js:1429:9
Backbone.Model@http://erp.manucentre.fr/web/static/lib/backbone/backbone.js:256:5
extend/child@http://erp.manucentre.fr/web/static/lib/backbone/backbone.js:1541:34
.pay_full_debt@http://erp.manucentre.fr/tg_pos_debt_notebook/static/src/js/tg_pos.js:119:38
.renderElement/<@http://erp.manucentre.fr/tg_pos_debt_notebook/static/src/js/tg_pos.js:96:54
```

Thanks in advance for your support

**Comment by flotho** [comment]
Hi,
@yelizariev  do you reproduce this error?

regards

**Comment by yelizariev** [comment]
@flotho 
I will check new updates in debt modules (see #62)   and then will check this issue

**Comment by flotho** [comment]
Hi @yelizariev ,

Any chance to have an idea of the merge date of your PR ?

**Comment by yelizariev** [comment]
@flotho We've merged #62 and I confirm your issue.

@ufaks there is also issue with debt value in Customer Page in POS: it is not updated after debt payment

**Comment by flotho** [comment]
Hi @yelizariev 

We still having an issue in the customer :

```

    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Lib_Odoo/v9-yelizariev_pos_addons/pos_debt_notebook/models.py", line 26, in _get_debt
    (debt_account.id, tuple(self.ids)))
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ERREUR:  l'opérateur n'existe pas : integer = boolean
LIGNE 3 :             WHERE l.account_id = false AND l.partner_id IN (...


```

**Comment by gaelTorrecillas** [comment]
hi, I have the same issue

**Comment by flotho** [comment]
HI @yelizariev ,

Personnaly I forced an update on the already exsiting module and it failed.
The code seems to inicates that the journal must be named XDEBT, isn't it too restrictive?
Wouldn't it be simplier to find the journal and afterwards use its account?

**Comment by flotho** [comment]
Additionnaly, could it be reluctant to use the already existing field for the customer balance?

**Comment by flotho** [comment]
https://github.com/yelizariev/pos-addons/pull/63

**Comment by obviousnikhil** [comment]
Hi @yelizariev ,

Are you still working on this issue? Do you think this issue will be fixed soon?

**Comment by yelizariev** [comment]
I think we will finish it next week.
Current work available here https://github.com/yelizariev/pos-addons/pull/92

**Comment by obviousnikhil** [comment]
Yes, I figured #92 and thanks for the update.

**Comment by yelizariev** [comment]
I close it, as update #92 is merged. Ping us if new issue happens
cc @ufaks
