### ISSUE TITLE
Do you have plans to port Pos_Packs to 9.0

### ISSUE THREAD

**Issue by treviser** [itpp-labs/pos-addons#65]
@yelizariev 
Do you have any plans already to port the pos_packs?
Thanks, trevi

**Comment by yelizariev** [comment]
I don't have such plans yet

**Comment by treviser** [comment]
What (or how much) would motivate you to do so?

**Comment by yelizariev** [comment]
Contact me if you need quotation yelizariev@it-projects.info

**Comment by cvinh** [comment]
Did you think of using MRP/BoM for doing product packs ? It would be more "Odoo standard"

**Comment by yelizariev** [comment]
@invitu I am not the author of the module. Probably, you are right and it has to be done via BOM

**Comment by treviser** [comment]
The same crosses my mind since days.

**Comment by treviser** [comment]
@invitu I see that you are also engaged in topics concerning restaurants. I want to use this module for example to compose dishes in the restaurant POS, i.e. selecting/changing sid dishes, toppings, addons and defining doneness of meat and I'm in the process of getting a quotation from IT-Projects. I'm selling/working on a vertical for diner restaurants, would you like to join forces? My email: trevi at twanda.com

**Comment by cvinh** [comment]
@yelizariev Yes Thierry Godin is the author but I think it has to be rewritten.
If we use BoM, we stay in odoo standard and we will only have javascript to develop. The Odoo models won't be affected...

**Comment by cvinh** [comment]
@treviser ok, then I let you work with @yelizariev but I could participate in specifying or testing
In my opinion there are 2 applications : 
- changing toppings, meat doneness...etc : it should be done with product attributes not with product pack. this approach has been taken by AgilOrg and Serpent CS in their vertical module. In first approach, if you want to work with standard Odoo, you can do it with products (pos category = addons). The advantage is that some option could be payable.
- making menus (starter, main course, dessert) : it should be made with pos_pack and BoM --> IT-Projects are very good for that development

Agilorg (v8) and Serpent CS (...-v9) did a very good job on restaurant. I think efforts should be put together.

**Comment by dansalsero** [comment]
Hi, the module pos_product_template does what you need and it uses variants. I'm using it on several clients.
