### ISSUE TITLE
A case where a running table disappears when using POS Multi Session

### ISSUE THREAD

**Issue by Abdullah7855** [itpp-labs/pos-addons#669]
There are multiple instances (may be 1 every second day) where a server opens a table, adds a few products and sends them to kitchen. However, the table doesn't show in other POS sessions. If the server refreshes the POS screen, the table disappears from servers POS screen. 

Any thoughts on why this might be happening? Thanks

**Comment by Abdullah7855** [comment]
I have not been able to reproduce the issue but here is the info I have been able to gather: 

1- Server opens a table (T9), adds items and sends to kitchen 
2- The table T9 is synced with 2nd POS session which is manned by cashier. 
3- Cashier prints bill and then validates the order of Table T9.  Table T9 is closed and shows up as empty on both POS sessions (I am not sure if T9 became closed/empty on server tablet).
4- The server picks up tablet to open table T5 in his session, adds items and sends to kitchen. However, two things happen:

(i) The server notices that table T9 Which was closed by cashier automatically re-appears in server POS session with all items but does not re-appear in cashier POS session. I am not sure if it ever got closed in server POS.

(ii) Table T5 isn't synced with cashier POS session. It only appears in server POS session who initiated that order. 

(iii) Both Server and Cashier refresh their POS screens with the hope that the order of Table T5 appears in cashier POS screen so that he can print bill for table T5. 

(iv) After POS screen refresh, both table T5 and T9 disappear (appear as empty tables) on both the cashier and server POS. 

I will report any other further information.

**Comment by yelizariev** [comment]
What do you mean saying *server do something* (Server opens a table)? Is it just a POS?
Also, do you mean the table is disappeared or order on the table?

Please note, that without strict scenario to reproduce the problem it's unlikely that we will investigate until you purchase it at apps store https://apps.odoo.com/apps/modules/11.0/pos_multi_session_restaurant/
