### ISSUE TITLE
[11.0] pos_multi_session: Can't add more than 1 POS

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#695]
When creating a multi-session, can't have more than one POS in the configuration
![image](https://user-images.githubusercontent.com/16890942/40344301-287ba756-5d62-11e8-971a-0bcce6cdb7fa.png)

**Comment by GabbasovDinar** [comment]
I confirm the issue
@KolushovAlexandr Can you fix it?

**Comment by gustavovalverde** [comment]
@KolushovAlexandr I'll like to QA the whole module for v11, if you could please fix it so I can make the QA for the whole process.

**Comment by gustavovalverde** [comment]
A this is an upstream problem (from Odoo); I'll be closing this one and testing with the proposed PR they have.
