### ISSUE TITLE
[9.0]Available products not displayed when pos_cache is used

### ISSUE THREAD

**Issue by flotho** [itpp-labs/pos-addons#72]
Hi @yelizariev 

when working with pos_cache, the value of available quantity don't seems to be loaded, Could it come from the fact that the available stock is computed thanks to location?

Could it be the same problem as : https://github.com/odoo/odoo/issues/10736

**Comment by yelizariev** [comment]
I think the problem here is that 
pos_cache is loaded after we load quantities, i.e. pos_cache just replaces products with qty_available field

So, what we need here is to find a way to load this code first:
https://github.com/odoo/odoo/blob/9.0/addons/pos_cache/static/src/js/pos_cache.js#L38
and only then this code:
https://github.com/yelizariev/pos-addons/blob/9.0/pos_product_available/static/src/js/pos.js#L13

I believe there should be a way to have a solution which works both with pos_cache and without one.

**Comment by flotho** [comment]
Hi @yelizariev ,

If I'm right, I could propose multiple ways to deal with this :
- To override load_server_data in your js so that the datas will be loaded by the pos_cache
- To override get_products_from_cache in .py so that it take laction in context. I think this one should be the easiest because there is no side-effect to add values in context, and we already have the pos.config so the location is available

What's your point of view?

**Comment by yelizariev** [comment]
I think we can extend load_server_data in my js. That is make something like in 8.0 version
https://github.com/yelizariev/pos-addons/blob/8.0/pos_product_available/static/src/js/pos.js#L5-L24
but we need to add in 9.0 version code as following

```
try{
    var models = require('pos_cache.pos_cache');
}
```

it will load pos_cache's load_server_data before our load_server_data
We need `try` here to make pos_product_available works without pos_cache too. If it will not help, we can create third autoinstallable module `pos_product_available_cache` with only lines in js:

require('pos_product_available.PosModel');
require('pos_cache.pos_cache');

I hope it makes loading in right order

**Comment by gaelTorrecillas** [comment]
hi @yelizariev 

what do you think about my PR?

**Comment by yelizariev** [comment]
@gaelTorrecillas
I have commented in #74

**Comment by yelizariev** [comment]
Done
https://github.com/yelizariev/pos-addons/commit/1921d979363bc0d4bdf357ca73ba94f8fdc2613b
Thank you for your contribution https://github.com/yelizariev/pos-addons/commit/0f0bfb68233c6ee024ecfb3821b7bcdbaba506e2
