### ISSUE TITLE
pos_mobile [10.0]

### ISSUE THREAD

**Issue by dhecar** [itpp-labs/pos-addons#728]
Hi, I have a problem with the pos_mobile module, specifically the search bar.
I'm on Android 7 (mobile with 3GB) and I use Chrome as a browser, but I've also tried opera.

The problem is that when you click on the search bar, the keyboard takes a few seconds to appear, this cau

ses the waiter to click several times in the search. This behavior causes the browser to freeze

In google chrome or chromium from pc in responsive mode, I see this message on the console, and I think it is caused by the lib jquery.nicescroll.js that is in the lib folder

that is the message:
[Violation] A non-passive event listener was added to a scroll lock event <some>. Consider marking the event handler as 'passive' to make the page more responsive. See <URL>

every time the waiter clicks, or I click to see what happens, the console fills up with these messages and I can no longer work, I have to kill the process and restart.

I'm just me who happens?

With what browser do you work so that this does not happen?

![capture](https://user-images.githubusercontent.com/4224295/43429053-b6d6a362-9461-11e8-80b8-03a5d5b83f1d.png)

**Comment by dhecar** [comment]
Hi ,after  searching i solved the problem, more or less.  I've disabled fastclick.js llibrary from point_of_sale because I think is not necessary with last browsers, and is not mantained anymore,  and I commented out from line 126 to 128  in  pos_mobile too.

            /*$('.searchbox input').click(function(){
                self.reset_category();
            });*/
now, the browser does not freeze and i can work well

I don't know if some one can take a look at this, for now I need to change the code of the module to work without delays and browsers does not freeze

**Comment by GabbasovDinar** [comment]
@dhecar Hello, I'll check soon

**Comment by yelizariev** [comment]
I made a PR to odoo (master branch). Thank you for report

**Comment by Ramil-Mukhametzyanov** [comment]
The patch for Odoo 10.0 in the pull-request https://github.com/it-projects-llc/pos-addons/pull/1110

**Comment by Ramil-Mukhametzyanov** [comment]
The patch for Odoo 11.0 in the pull-request https://github.com/it-projects-llc/pos-addons/pull/1149
