### ISSUE TITLE
hw_printer_network support for cashdrawer

### ISSUE THREAD

**Issue by tobru** [itpp-labs/pos-addons#730]
When I understand the code correctly there is no support for opening a cash drawer connected to a network printer. The [upstream code](https://github.com/odoo/odoo/blob/master/addons/hw_proxy/controllers/main.py#L204) has a http route `/hw_proxy/open_cashbox` which is missing in `hw_printer_network/controllers/hw_printer_network_controller.py`. If I understand this correctly, are there any plan to support cashdrawers connected to network printers?

**Comment by tobru** [comment]
On the server / posbox side this would add this feature:

```
--- hw_printer_network_controller.py.orig	2018-08-07 18:31:13.764291153 +0000
+++ hw_printer_network_controller.py	2018-08-07 19:47:19.238985467 +0000
@@ -129,6 +129,21 @@
                             # add a missed order to queue
                             time.sleep(3)
                             self.queue.put((timestamp, task, data))
+                elif task == 'cashbox':
+                    printer_info = self.get_network_printer(data)
+                    printer = self.printer_objects.get(data, None)
+                    if printer_info and printer_info['status'] == 'online' and printer:
+                        _logger.info('Opening cashbox on printer %s...', data)
+                        try:
+                            printer.cashdraw(2)
+                            printer.cashdraw(5)
+                        except socket.error:
+                            printer.open()
+                            printer.cashdraw(2)
+                            printer.cashdraw(5)
+                        _logger.info('Done opening cashbox on printer %s', data)
+                    else:
+                        _logger.error('cashbox: printer offline!')
                 elif task == 'printstatus':
                     pass
                 elif task == 'status':
@@ -172,6 +187,14 @@
         else:
             super(UpdatedEscposProxy, self).print_xml_receipt(receipt)
 
+    @http.route('/hw_proxy/open_cashbox', type='json', auth='none', cors='*')
+    def open_cashbox(self, proxy=None):
+        _logger.info('Open cashbox via network printer') 
+        if proxy:
+            network_driver.push_task('cashbox', proxy)
+        else:
+            super(UpdatedEscposProxy, self).cashbox()
+
     @http.route('/hw_proxy/network_printers', type='json', auth='none', cors='*')
     def network_printers(self, network_printers=None):
         for printer in network_printers:

```

But on the Odoo side (PoS web view) the "proxy" variable is missing, so this function is never called. I'm not really experienced with extending Odoo, so I must leave this up to someone who is able to do it. It most probably has to be added to the `pos_printer_network` add-on.

**Comment by GabbasovDinar** [comment]
@tobru 

> But on the Odoo side (PoS web view) the "proxy" variable is missing, so this function is never called. I'm not really experienced with extending Odoo, so I must leave this up to someone who is able to to it. It most probable has to be added to the pos_printer_network add-on.

yes, I send new parameter ``proxy`` to PosBox

```
                var send_printing_job = function(){
                    if(self.receipt_queue.length > 0) {
                        var r = self.receipt_queue.shift();
                        self.connection.rpc('/hw_proxy/print_xml_receipt', {
                            receipt: r,
                            proxy: network_proxy
                        }, {timeout: 5000}).then(function () {
                            send_printing_job();
                        }, function () {
                            self.receipt_queue.unshift(r);
                        });
                    }
                };
```
but this proxy address for network printer only, I think we need to use a new proxy address for network cash drawer

**Comment by UnixedIT** [comment]
Hello @tobru 
Did you find the final solution ? please advise, I face the same problem.

**Comment by shabeervpk** [comment]
**Also Update**
/pos_printer_network/static/src/js/network_printer.js


message : function(name,**params = {}**){
            if (**(name === 'print_xml_receipt' || name === 'open_cashbox' )** && this.pos.config.receipt_printer_type === "network_printer") {
                var connection = new Session(void 0, this.pos.proxy.host, {
                    use_cors: true
                });
                var callbacks = this.notifications[name] || [];
                for(var i = 0; i < callbacks.length; i++){
                    callbacks[i](params);
                }
                params.proxy = this.pos.config.receipt_network_printer_ip;
                if(this.get('status').status !== 'disconnected'){
                    return connection.rpc('/hw_proxy/' + name, params || {});
                }
                return (new $.Deferred()).reject();
            }
            return this._super(name, params);
        },

**Comment by GabbasovDinar** [comment]
I think also we can add one line of code to XML Receipt <cashdraw/>

https://github.com/odoo/odoo/blob/12.0/addons/hw_escpos/escpos/escpos.py#L692

**Comment by GabbasovDinar** [comment]
feel free to send a PR with the changes :smile:
