### ISSUE TITLE
[QUESTION] multissesion sync

### ISSUE THREAD

**Issue by dhecar** [itpp-labs/pos-addons#741]
Hello, it's possible to sync information trought terminals but avoid the screen to go to top or bottom when the sync is done?

If for some reason in one terminal i'm looking for something (note in plate or other thing) and I scrolled to specific point, if someone do a change in the other terminal, the scroll go to the end of the order and I need search the line i need to see again.

**Comment by GabbasovDinar** [comment]
@dhecar Hello, which version of Odoo? I will check

**Comment by dhecar** [comment]
I'm on version 10.
[vokoscreen-2018-08-28_05-15-59.mkv.zip](https://github.com/it-projects-llc/pos-addons/files/2326356/vokoscreen-2018-08-28_05-15-59.mkv.zip)

**Comment by GabbasovDinar** [comment]
@dhecar Yes, it is a problem for the same orders only. 

It most likely that we will work on this issue only if you provide proof of the payment for this module
https://www.odoo.com/apps/modules/11.0/pos_multi_session_restaurant/

**Comment by dhecar** [comment]
@GabbasovDinar No, if I make a change in other order i get the same, every sync make an update in all orders and move the scroll

**Comment by Ramil-Mukhametzyanov** [comment]
@dhecar Hello, we have tested versions 10.0, 11.0 and 12.0 for this problem. Order scrolling causes only for the same order.
This is because the user must see the total order amount to ensure before making the payment.
Do you have any other suggestions on this subject?
