### ISSUE TITLE
[REQUEST] POS Create Invoice

### ISSUE THREAD

**Issue by gregimagines** [itpp-labs/pos-addons#759]
You have the option of pulling up sales orders and invoices and paying them using pos_invoice. However we are looking for the inverse options. We would like an option to bill a customer's account (especially if they are net30, etc) instead of paying immediately. ie. A customer comes into the store, and picks up some items for their business. We can ring them up in POS, and their account is billed instead of them being forced to pay immediately or us jumping around making invoices. Ideally a button on the payment options that invoices their account instead of cash/credit.
For use with Version 11

**Comment by ilmir-k** [comment]
@gregimagines 
As I understand you would like to have an option to create invoice(s) for selected customer from POS payment screen, right?

The flow maybe as follows:
* select a customer and add the items in POS
* go to payment screen
* click, for example, new _Create Invoice_ button
* once the button is clicked, new draft invoice is created in backend

Please confirm

**Comment by gregimagines** [comment]
That is exactly what I’m looking for, yes. Once button is clicked, invoice is created in backend and POS can go to the next order without having to take a payment on the invoiced one.

**Comment by ilmir-k** [comment]
@gregimagines 
Ok, I've got it and we could help you, but it should be noted that we can't make it for free. Please email to it@it-projects.info to receive a quotation for this customization.
