### ISSUE TITLE
Cannot define max debt per customer in new version of the module pos_debt_notebook

### ISSUE THREAD

**Issue by hydrosIII** [itpp-labs/pos-addons#761]
In the version    11.0.5.0.2, there is no an option to define pos_max_debt. I am not sure if this a bug or  something that was planned feature since there has been a lot of changes to the module, or if define  max debt can be now done via another module.

v 11.0.5.0.2 commit: 22b46035d48da8b5df99263454cf6d49eb76a7be

Version 11.0.4.4.3 has this option to define max debt.

v. 11.0.4.4.3 commit: 30fc34030d0291ef7774d5cddd0ba14d45490f03

Odoo 11 Enterprise.
I30fc34030d0291ef7774d5cddd0ba14d45490f03

**Comment by yelizariev** [comment]
It's true. See discussion in https://github.com/it-projects-llc/pos-addons/commit/dc4f1bb13449e341fa447d6fdb3fa44e72401266#commitcomment-30540148
