### ISSUE TITLE
[9.0-pos_multi_session] "added by/edited by" should refer to "cashier" instead of "Pos name"

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#78]
Steps to reproduce : 
- Configure a pos1 with shared session between cashiers
- Log in pos1 session with cashier1
- Add products in the order --> added by pos1
- Change cashier in the pos --> cashier2
- Add products in the order --> edited by pos1

Expected behaviour : 
it should be added by cashier1 / edited by cashier2

**Comment by yelizariev** [comment]
"Added by ..." tells Pos Name, not Cashier Name 

```

<?xml version="1.0" encoding="UTF-8"?>
<templates id="template" xml:space="preserve">
    <t t-extend="Orderline">
        <t t-jquery=".info-list" t-operation="after">
            <div t-if="line.ms_info and line.ms_info.created" class="ms_info">
                added by <t t-esc="line.ms_info.created.pos.name"/>
                <t t-if="line.ms_info.changed and line.ms_info.changed.pos.id != line.ms_info.created.pos.id">
                    , edited by <t t-esc="line.ms_info.changed.pos.name"/>
                </t>
            </div>
        </t>
    </t>
    <t t-extend="OrderSelectorWidget">
        <t t-jquery=".order-sequence" t-operation="append">
            <span t-if="order.ms_info and order.ms_info.created" class="ms_info"><t t-esc="order.ms_info.created.pos.name"/></span>
        </t>
    </t>
</templates>

```

**Comment by cvinh** [comment]
Thanks for correcting... By the way don't you think it would be better to have cashier name ? In case pos is shared between several cashiers I think it's better to track 'who' added items instead of 'from which pos'.
In the case pos is not shared, tracking cashier is also a good behaviour.

**Comment by yelizariev** [comment]
But what do you think about OrderSelectorWidget?
There is no space to put there Cashier name.
Do you thinks it is ok to keep there Pos name (e.g. POS1), while in Order put line "added by CasherName".

**Comment by yelizariev** [comment]
Idea!
OrderSelectorWidget: POS1
Orderline: added by CasherName (POS1)

**Comment by cvinh** [comment]
Of course ! I agree

**Comment by yelizariev** [comment]
Done
