### ISSUE TITLE
[12.0] Port pos_debt_notebook

### ISSUE THREAD

**Issue by carlosrve** [itpp-labs/pos-addons#780]
I am creating this issue to discuss update of the pos_debt_notebook module.

**Comment by carlosrve** [comment]
As of now, we just removed the base_groupby_extra dependency and inheritance, changed the uom reference to the new uom module and added the missing name attribute in the search views. Everything seems to work OK. We are running some functional tests.

**Comment by yelizariev** [comment]
base_groupby_extra is not needed in 12 as that feature is built-in now. So, looks like you are on correct path :+1:

**Comment by TheCloneMaster** [comment]
This one is completed...

**Comment by KolushovAlexandr** [comment]
Thanks for contributing,
The module was ported to 12.0 here https://github.com/it-projects-llc/pos-addons/pull/815
