### ISSUE TITLE
[9.0 pos_multi_session] customer do not sync between poses

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#80]
Steps to reproduce :

Configure a pos with shared session between users
Log in pos session with user1
Choose customer in the order
The customer is not synchronized in the other poses

Expected behaviour : 
customer should be synchronized

**Comment by cvinh** [comment]
I think MindAndGo already work on that : https://github.com/MindAndGo/pos-addons/commit/31bfdc2c5c0dcfe190c91573f494268f35af4ed7#diff-69280bd2879a0334b3dadb77af444094

**Comment by cvinh** [comment]
Duplicate of https://github.com/yelizariev/pos-addons/issues/70

**Comment by cvinh** [comment]
I reopen the issue since MindAndGo 's branch is not merged with yours

**Comment by yelizariev** [comment]
Updates are prepared in #77 by @ilyasProgrammer

**Comment by yelizariev** [comment]
done
