### ISSUE TITLE
[9.0 pos_multi_session_restaurant] guests do not sync between poses

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#81]
Steps to reproduce :

Configure a pos restaurant with shared session between users
Log in pos session with user1
Make an order
Change Guests in the order
The guest number is not sync between poses

Expected behaviour : 
guest number should be synchronized

**Comment by yelizariev** [comment]
Thanks for reporting. I've added this and #82 #83 to todo list

**Comment by yelizariev** [comment]
done
