### ISSUE TITLE
[11][pos_restaurant_base] this is window instead of order

### ISSUE THREAD

**Issue by ruben-tonetto** [itpp-labs/pos-addons#819]
in print_order_receipt function this is global variable window, instead of order.
so variable widged passed to receipt doesn't contain order data

maybe:

$.proxy( function(){
                    var receipt = QWeb.render('OrderChangeReceipt',{changes:changes, widget:this});
                    printer.print(receipt);
                    return delay(100);
                }, this )

**Comment by GabbasovDinar** [comment]
Hello @ruben-tonetto 

Yes, you are right. We need to use `self ` instead `this`

**Comment by GabbasovDinar** [comment]
@yelizariev This error is present in all versions. I will fix for 10.0 but we need to port to newer versions (11.0 and 12.0)

**Comment by ruben-tonetto** [comment]
Mmm... did you test it?
self is a reference to this, but when this changes to window, self refers to window.
i've tested and seems not working

PS: thanks for your projects

**Comment by GabbasovDinar** [comment]
@ruben-tonetto How did you test it?

I don't have the error

![untitled](https://user-images.githubusercontent.com/15119940/48614091-3efb3800-e9af-11e8-8d9e-10f5eb3bbe7c.png)

**Comment by ruben-tonetto** [comment]
Sorry, you are right!
It works
thanks

Il giorno ven 16 nov 2018 alle ore 10:52 Dinar <notifications@github.com>
ha scritto:

**Comment by gustavovalverde** [comment]
@GabbasovDinar this can be closed

**Comment by GabbasovDinar** [comment]
@yelizariev Please, close the issue
