### ISSUE TITLE
[9.0 pos_multi_session_restaurant] order state do not synchronize between poses

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#82]
Steps to reproduce :

Configure a pos restaurant with shared session between users and printers for kitchen (printer_ids)
Log in pos session with user1
Make an order with printable products
Clic on "Order" button to print the order
The state of the order is not sync between poses

Expected behaviour : 
order state should be synchronized

**Comment by invitu** [comment]
I did a PR here #79 but it was bad as orderline notes come from pos_restaurant
Changes should be done in pos_multi_session_restaurant module

**Comment by cvinh** [comment]
Hello
I just tested last commit. Works very well ! except this small bug : 

Steps to reproduce :
- Configure a pos restaurant with shared session between users and printers for kitchen (printer_ids)
- Log in pos session with user1 
- Make an order with printable products
- Clic on "Order" button to print the order
- The state of orderlines is well synchronized between poses but the Order Button stays green. If we click on Order Button, added by/edited by goes wrong... (I did not test if the kitchen receipt is printed or not)

Expected behaviour : 
Order Button should be unclickable after it has been clicked on the other pos

**Comment by yelizariev** [comment]
@invitu 
have you checked this note
https://github.com/yelizariev/pos-addons/tree/9.0/pos_multi_session_restaurant#local-run

**Comment by cvinh** [comment]
I tested it without dbfilter, on a local server.

**Comment by yelizariev** [comment]
@invitu 
I confirm both bugs:
issue with **edited by** label
![1458727480597screensave](https://cloud.githubusercontent.com/assets/186131/13981892/b1af3e34-f108-11e5-8c2c-a49c1fda3104.png)

issue with Order button
![1458727824864screensave](https://cloud.githubusercontent.com/assets/186131/13982021/6de0c582-f109-11e5-82c2-6739816873d2.png)

**Comment by cvinh** [comment]
I think it's useful to keep the "edited by Administrator" if Administrator pushed the green button... because Administrator did something (he printed the order, so he did something...)

On the other hand, not synchronizing the Order button is not good... Did you click on the green order button ? in my case, the "added by/edited by" information goes bad

**Comment by yelizariev** [comment]
> "added by/edited by" information goes bad

what do you mean? When I click it adds "edited by Administrator"  only

**Comment by cvinh** [comment]
if you click on the button on Administrator POS, it adds "edited by Administrator"
Now go on the other POS and click on the green button.
In my test, the "added by/edited by" information is reset

**Comment by yelizariev** [comment]
Yes, because we doesn't show "edited by" if it equal to "created by"

```
            <t t-if="line.ms_info.changed and line.ms_info.changed.pos.id != line.ms_info.created.pos.id">
```

**Comment by yelizariev** [comment]
```
<t t-extend="Orderline">
    <t t-jquery=".info-list" t-operation="after">
        <div t-if="line.ms_info and line.ms_info.created" class="ms_info">
            added by <t t-esc="line.ms_info.created.user.name"/> (<t t-esc="line.ms_info.created.pos.name"/>)
            <t t-if="line.ms_info.changed and line.ms_info.changed.pos.id != line.ms_info.created.pos.id">
                , edited by <t t-esc="line.ms_info.changed.user.name"/>  (<t t-esc="line.ms_info.changed.pos.name"/>)
            </t>
        </div>
    </t>
</t>
```

**Comment by yelizariev** [comment]
I suggest don't change  "edited by" at all when user just click "Order". Does it matter who clicked "Order"? It just prints ticket in the kitchen. Not a big problem

**Comment by yelizariev** [comment]
It simple solution for this issue

**Comment by cvinh** [comment]
> don't change "edited by" at all when user just click "Order".

Ok it makes sense
