### ISSUE TITLE
[9.0 pos_multi_session_restaurant] orderline notes do not synchronize between poses

### ISSUE THREAD

**Issue by cvinh** [itpp-labs/pos-addons#83]
Steps to reproduce :

Configure a pos restaurant with shared session between users
Log in pos session with user1
Make an order
Add a note on orderline
The note is not sync in user2 pos session

Expected behaviour : 
orderline notes should be synchronized

**Comment by cvinh** [comment]
I did a PR here #79 but it was bad as orderline notes come from pos_restaurant
Changes should be done in pos_multi_session_restaurant module

**Comment by yelizariev** [comment]
Done.
I've applied it in pos_multisession as you did. 
https://github.com/yelizariev/pos-addons/commit/b2358fbe105e5d71486bfe507409d0750530ad2c
