### ISSUE TITLE
migrate some modules to Flectra

### ISSUE THREAD

**Issue by eabellom** [itpp-labs/pos-addons#965]
I'm trying to migrate some modules to Flectra, especially pos_multi_session ..... can I ask in this group in reference to this? ... Is there an initiative around this topic on your part?
Thanks

**Comment by trojikman** [comment]
@yelizariev

**Comment by yelizariev** [comment]
We don't have such plans. But you may sponsor the development. Contact IT-Projects by email it@it-projects.info.

I close this issue as it's not related to the repository directly
