### ISSUE TITLE
pos_longpolling: Error: QWeb2: Template 'synch_icon' not found

### ISSUE THREAD

**Issue by Noirvent** [itpp-labs/pos-addons#983]
Hello,
I tried installing several addons of your repo on my Odoo 11 instance, like pos_orders_history and pos_invoice_pay

But when I launch the POS, it load and stay stuck on a black screen, with the following error in the console:

`Error: QWeb2: Template 'synch_icon' not found`

I pinpointed this in the pos_longpolling module that both modules share as dependency, but I don't really know what to do to fix that.

Can you help me ?

**Comment by GabbasovDinar** [comment]
Hello @Noirvent 
Thank you for the report. I don't have this problem. Do you use the latest version of modules? Can you send me the logs?

**Comment by AsmakTharaa** [comment]
Is there any update on this? I am having the same issue

**Comment by nabilelkadiri** [comment]
Hi, same issue on Odoo v10.0 CE with the latest updated module files, same error message blocking pos from loading

Can you please assist?

**Comment by chafarleston** [comment]
I got this issue recently, is for two factor the addons folder should be 775(use chmod -R 775 /the name of the folder), and the owner of the folder should be odoo(or the name user that you use examp  sudo chown odoo12:odoo12 odoo-custom-addons/* )

**Comment by yelizariev** [comment]
@chafarleston thanks for sharing this information. I think we can close the issue
