### ISSUE TITLE
[pos_keyboard] Enter key not working (v10)

### ISSUE THREAD

**Issue by Ark74** [itpp-labs/pos-addons#985]
I just found about the new features pushed by @KolushovAlexandr on this addon, amazing job btw.

**What happens,**
I've found that the Enter Key is not responding on v10, not the Enter key nor the NumPad one.

I've tested both for this issue (enter key),
* Odoo v11 (bc6d051fcab9a6552968683a095b34cb3b937aff) + 
pos_keyboard v11.0.1.1.0 = **works!**
* Odoo v10 (903fec011d64cd50a4e925d4046757afacf1363a) + 
pos_keyboard v10.0.1.1.1 = **doesn't work.**

Any other key is working as it should.
I looked for a runbot to confirm the behavior but seems they are not available.

Best regards.

**Comment by KolushovAlexandr** [comment]
Thanks for reporting! Fixed here https://github.com/it-projects-llc/pos-addons/pull/999
